uklvapapp799 ansible_host=uklvapapp799.gdc.standardchartered.com ansible_connection=ssh ansible_port=22  ansible_user=tsp-release web_deploy_dir=/apps/tsp/html
uklvasapp799 ansible_host=uklvasapp799.gdc.standardchartered.com ansible_connection=ssh ansible_port=22  ansible_user=tsp-release web_deploy_dir=/apps/tsp/html
hklvapapq761 ansible_host=hklvapapq761.hk.standardchartered.com ansible_connection=ssh ansible_port=22  ansible_user=tsp-release web_deploy_dir=/apps/stg-tsp/html
hklvasapq761 ansible_host=hklvasapq761.hk.standardchartered.com ansible_connection=ssh ansible_port=22  ansible_user=tsp-release web_deploy_dir=/apps/stg-tsp/html

[stg_app_server]
uklvapapp799
uklvasapp799
hklvapapq761
hklvasapq761

[all_server]
uklvapapp799
uklvasapp799
hklvapapq761
hklvasapq761

[web_server]
uklvapapp799
uklvasapp799
hklvapapq761
hklvasapq761

[stg_app_server:vars]
env=Stage
maven_package_repo_dir=maven-sc-release_local
npm_package_repo_dir=npm-release
generic_package_repo_dir=generic-release
docker_repo=artifactory.global.standardchartered.com
cdn_url_prefix=https://stg-cdn.leap.standardchartered.com
eurekaDefaultZone=https://uklvapapp632.gdc.standardchartered.com:8761/eureka,https://uklvasapp632.gdc.standardchartered.com:8761/eureka,https://uklvapapp799.gdc.standardchartered.com:8761/eureka,https://uklvasapp799.gdc.standardchartered.com:8761/eureka

[all_server:vars]
artifact_repo=https://artifactory.global.standardchartered.com/artifactory
temp_deploy_dir=/tmp/tsp
apps_logs_dir=/apps/tsp/logs/
region=uk
python_path=/apps/tsp/python-env/bin/python
pip_path=/apps/tsp/python-env/bin/pip
db_password_file=/apps/tsp/security/aLicence.txt
ld_library_path=/usr/lib/oracle/12.1/client64/lib/
service_script=/usr/sbin/service
app_deploy_dir=/apps/tsp
web_deploy_dir=/apps/tsp/html
httpd_dir=/etc/httpd
apache2_dir=/usr/local/apache2
apache24_dir=/usr/local/apache24
