import type { TradeRow } from './tradeBlotterTypes';
import { PENDING_VALIDATION_STATUS } from './tradeBlotterTypes';

export const TRADE_ROWS: TradeRow[] = [
  {
    tradeId: 'TR-001',
    book: 'Rates',
    desk: 'LDN',
    status: PENDING_VALIDATION_STATUS,
    counterparty: 'GS',
    notional: 1200000,
  },
  {
    tradeId: 'TR-002',
    book: 'FX',
    desk: 'SG',
    status: PENDING_VALIDATION_STATUS,
    counterparty: 'MS',
    notional: 2500000,
  },
  {
    tradeId: 'TR-003',
    book: 'Equities',
    desk: 'NY',
    status: PENDING_VALIDATION_STATUS,
    counterparty: 'CITI',
    notional: 980000,
  },
  {
    tradeId: 'TR-004',
    book: 'Commodities',
    desk: 'HKG',
    status: PENDING_VALIDATION_STATUS,
    counterparty: 'BARX',
    notional: 740000,
  },
  {
    tradeId: 'TR-005',
    book: 'Rates',
    desk: 'NY',
    status: PENDING_VALIDATION_STATUS,
    counterparty: 'JPM',
    notional: 3100000,
  },
  {
    tradeId: 'TR-006',
    book: 'FX',
    desk: 'LDN',
    status: PENDING_VALIDATION_STATUS,
    counterparty: 'UBS',
    notional: 1660000,
  },
  {
    tradeId: 'TR-007',
    book: 'Credit',
    desk: 'SG',
    status: PENDING_VALIDATION_STATUS,
    counterparty: 'HSBC',
    notional: 2040000,
  },
  {
    tradeId: 'TR-008',
    book: 'Macro',
    desk: 'TKY',
    status: PENDING_VALIDATION_STATUS,
    counterparty: 'BNP',
    notional: 870000,
  },
  {
    tradeId: 'TR-009',
    book: 'Rates',
    desk: 'SG',
    status: PENDING_VALIDATION_STATUS,
    counterparty: 'DB',
    notional: 1290000,
  },
  {
    tradeId: 'TR-010',
    book: 'FX',
    desk: 'NY',
    status: PENDING_VALIDATION_STATUS,
    counterparty: 'BAML',
    notional: 4200000,
  },
  {
    tradeId: 'TR-011',
    book: 'Credit',
    desk: 'LDN',
    status: PENDING_VALIDATION_STATUS,
    counterparty: 'RBC',
    notional: 1110000,
  },
  {
    tradeId: 'TR-012',
    book: 'Equities',
    desk: 'SG',
    status: PENDING_VALIDATION_STATUS,
    counterparty: 'SOCGEN',
    notional: 540000,
  },
  {
    tradeId: 'TR-013',
    book: 'Credit',
    desk: 'NY',
    status: 'VALIDATED',
    counterparty: 'JPM',
    notional: 1800000,
  },
];
