trigger: none

parameters:
  - name: releaseId
    type: string
    displayName: Release WorkItem ID
    default: 0
  - name: rollbackAppVersion
    type: string
    displayName: Rollback App Version
    default: 0
  - name: rollbackBuildNumber
    type: string
    displayName: Rollback Build Number
    default: 0
  - name: subComponentId
    type: string
    displayName: Sub Component ID
    default: 'None'
  - name: deployEnv
    type: string
    displayName: Deploy to VM or AWS (only for develop branch)
    default: vm
    values:
      - vm
      - eks
      - sit
      - demo
  - name: runDevStage
    type: boolean
    displayName: Deploy DEV
    default: false
    values:
      - true
      - false

variables:
  - name: APP_NAME
    value: ${{ replace(variables['Build.Repository.Name'], '51358-', '') }}

resources:
  repositories:
    - repository: templates
      ref: main
      name: FMQPR/51358-ratanone-ado-templates
      type: git

extends:
  template: nodejs-mfe.yml@templates
  parameters:
    releaseId: ${{ parameters.releaseId }}
    packageVersion: 1.46.0
    deployStack: ansible
    deployEnv: ${{ parameters.deployEnv }}
    rollbackAppVersion: ${{ parameters.rollbackAppVersion }}
    rollbackBuildNumber: ${{ parameters.rollbackBuildNumber }}
    subComponentId: ${{ parameters.subComponentId }}
    runDevStage: ${{ parameters.runDevStage }}
    sonarCoverageExclusions: "**/test/**, **/interface.ts, **/mock.ts, **/Cashflow_CN/Main/config/ratanConfig/**"
    featureRelease: true
