import { GridColDef } from "@mui/x-data-grid";
import React from "react";

import { TileProps } from "./interface";
declare const useController: (_props: TileProps) => {
  store: import("../../../hooks/model/root").RootModel;
  onCreateNew: () => void;
  columns: GridColDef<any, any, any>[];
  rows: any;
  onClose: () => void;
  onOpen: (row: any, mode: any) => () => void;
  onChange: (value: any, field: string) => void;
  openDetail: boolean;
  record: any;
  onReset: () => void;
  onSave: () => Promise<void>;
  onSaveData: (result: any) => Promise<void>;
  resetId: number;
  onVerify: () => Promise<void>;
  onUpdate: () => Promise<void>;
  onUpdateData: (result: any) => Promise<void>;
  isLoading: boolean;
  onDeactivate: () => Promise<void>;
  auditColumns: GridColDef<any, any, any>[];
  auditRows: any;
  openAudit: boolean;
  onCloseAudit: () => void;
  tile: undefined;
  setTile: React.Dispatch<React.SetStateAction<undefined>>;
  categories: any;
  category: any;
  onCategoryChange: (_event: any, newValue: any) => void;
  onInputChange: (_event: any, newInputValue: any) => void;
  inputValue: string;
  onOpenAudit: (row: any) => () => void;
  getAuditData: (_tile: any) => void;
  setCategories: React.Dispatch<any>;
  setOriginalCategories: React.Dispatch<any>;
  getCategoryData: (_category: any) => void;
  refresh: () => void;
  initData: () => void;
  setCategoryData: (_data: any) => void;
  disableCreateNew: boolean;
};
export default useController;
