import { fn } from "@Test/test-utils";
import {
  AgGridEvent,
  Column,
  GetContextMenuItemsParams,
  IMenuActionParams,
  RowNode,
} from "ag-grid-community";

export const mockAggridEvent = {
  api: {
    updateRowData: () => ({
      add: [],
      remove: [],
      update: [],
    }),
    getAllDisplayedColumns: fn(() => [
      {
        getColDef: () => ({ field: "test" }),
        colDef: {
          field: "test",
        },
      },
    ]),
    applyTransaction: fn(),
    getRowNode: fn(() => ({})),
    refreshCells: fn(),
    flashCells: fn(),
    showNoRowsOverlay: fn(),
    showLoadingOverlay: fn(),
    hideOverlay: fn(),
    setRowData: fn(),
    forEachNode: fn((cb) => {
      cb({ data: null });
    }),
    exportDataAsCsv: fn(),
    exportDataAsExcel: fn(),
    paginationGetPageSize: fn(),
    paginationGetCurrentPage: fn(),
    getSelectedRows: fn(() => []),
    getGridOption: fn(),
    setGridOption: fn(),
    getColumn: fn(),
    setServerSideDatasource: fn(),
    dispatchEvent: fn(),
    getLastDisplayedRowIndex: fn(() => 0),
    getDisplayedRowCount: fn(() => 1),
    ensureIndexVisible: fn(),
  },
} as unknown as AgGridEvent;

export const mockGetContextMenuItemsParams: (
  data
) => GetContextMenuItemsParams = (data) => ({
  defaultItems: [],
  column: fn() as unknown as Column,
  node: {
    mainEventService: undefined,
    gridOptionsWrapper: undefined,
    selectionController: undefined,
    columnController: undefined,
    valueService: undefined,
    rowModel: undefined,
    context: undefined,
    valueCache: undefined,
    gridApi: undefined,
    id: "",
    groupData: undefined,
    aggData: undefined,
    data: data,
    parent: null,
    level: 0,
    uiLevel: 0,
    rowGroupIndex: null,
    group: undefined,
    dragging: false,
    master: false,
    detail: false,
    detailNode: null,
    detailGridInfo: null,
    leafGroup: false,
    firstChild: false,
    lastChild: false,
    childIndex: 0,
    rowIndex: 0,
    rowPinned: "",
    quickFilterAggregateText: "",
    footer: false,
    field: null,
    rowGroupColumn: null,
    key: undefined,
    stub: false,
    allLeafChildren: [],
    childrenAfterGroup: [],
    childrenAfterFilter: [],
    childrenAfterSort: [],
    allChildrenCount: null,
    childrenMapped: null,
    childrenCache: null,
    expanded: false,
    sibling: null,
    rowHeight: 0,
    rowHeightEstimated: false,
    rowTop: 0,
    oldRowTop: 0,
    daemon: false,
    selectable: false,
    __cacheData: {},
    __cacheVersion: 0,
    __objectId: 0,
    __hasChildren: undefined,
    alreadyRendered: false,
    highlighted: null,
    selected: undefined,
    eventService: undefined,
  } as unknown as RowNode,
  value: undefined,
  api: mockAggridEvent.api,
  context: undefined,
});

// @ts-ignore
export const mockRowNode: (d) => RowNode = (data) => ({
  mainEventService: undefined,
  gridOptionsWrapper: undefined,
  selectionController: undefined,
  columnController: undefined,
  valueService: undefined,
  rowModel: undefined,
  context: undefined,
  valueCache: undefined,
  gridApi: undefined,
  id: "",
  groupData: null,
  aggData: undefined,
  data,
  parent: null,
  level: 0,
  uiLevel: 0,
  rowGroupIndex: null,
  group: undefined,
  dragging: false,
  master: false,
  detail: false,
  detailNode: null as any,
  detailGridInfo: null,
  leafGroup: false,
  firstChild: false,
  lastChild: false,
  childIndex: 0,
  rowIndex: 0,
  rowPinned: null,
  quickFilterAggregateText: "",
  footer: false,
  field: null,
  rowGroupColumn: null,
  key: null,
  stub: false,
  allLeafChildren: [],
  childrenAfterGroup: [],
  childrenAfterFilter: [],
  childrenAfterSort: [],
  allChildrenCount: null,
  childrenMapped: null,
  childrenCache: null,
  expanded: false,
  sibling: null as any,
  rowHeight: 0,
  rowHeightEstimated: false,
  rowTop: 0,
  oldRowTop: 0,
  daemon: false,
  selectable: false,
  __cacheData: {},
  __cacheVersion: 0,
  __objectId: 0,
  __hasChildren: undefined,
  alreadyRendered: false,
  highlighted: null,
  selected: undefined,
  eventService: undefined,
});

export const mockMenuActionParams = (): IMenuActionParams => {
  return {
    column: null,
    node: null,
    api: mockAggridEvent.api,
    value: null,
    context: null,
  };
};
