export const mockCashflow1 = {
  BCS_Trade_Id: "1816352",
  BCS_Parent_Trade_Id: "1816352",
  FMO_Comments: null,
  Cashflow: {
    Cashflow_Id: "008690236385",
    Cashflow_Business_Version: 0,
    Cashflow_Version: 0,
    Cashflow_State: "WAITING",
    Cashflow_Affirmation_Status: "affirmed",
    Cashflow_Event_Type: "New",
    Cashflow_Minor_Version: 4,
    Payment_Currency: "USD",
    Payment_Date: "2022-03-11",
    Payment_Type: "netAmount",
    Payment_Cutoff_Time: "2022-03-10T00:00",
    Pay_Receive_Indicator: "Pay",
    Payment_Amount: "1000",
    Netting_Id: "",
    Netting_Cuttoff_Date: "null",
    Payment_Receiver_Party_Reference: "party2",
    Payment_Payer_Party_Reference: "party1",
    Cashflow_Sub_State: "Pending Verification",
    Cashflow_Sub_State_Type: "Pending Exception",
    Cashflow_Sub_State_Updater: "1470797",
    Status_Event_Type: "",
    Event_Date: "2022-10-20",
  },
  Delivery_Method: "",
  Settlement_Method: "Cash",
  Trade_Id: "1816352",
  Trade_Version: 0,
  Entity: {
    Booking_Entity_SCI_FMID: "10075222",
    Booking_Entity_SCI_FMCODE: null,
    Counterparty_SCI_FMID: "400640613",
    Counterparty_SCI_FMCODE: null,
  },
  Parent_Trade_Id: "1816352",
  Trade_State: "VALIDATED",
  Portfolio: {
    Booking_Entity_Trade_Portfolio_Name: "BCS_FSS_UK_BTBLTQ",
  },
};

export const mockCashflowHold = {
  BCS_Trade_Id: "1816352",
  BCS_Parent_Trade_Id: "1816352",
  FMO_Comments: null,
  Cashflow: {
    Cashflow_Id: "008690236385",
    Cashflow_Business_Version: "0",
    Cashflow_Version: 0,
    Cashflow_State: "HOLD",
    Cashflow_Affirmation_Status: "affirmed",
    Cashflow_Event_Type: "New",
    Cashflow_Minor_Version: "4",
    Payment_Currency: "USD",
    Payment_Date: "2022-03-11",
    Payment_Type: "netAmount",
    Payment_Cutoff_Time: "2022-03-10T00:00",
    Pay_Receive_Indicator: "Pay",
    Payment_Amount: "1000",
    Netting_Id: "",
    Netting_Cuttoff_Date: "null",
    Payment_Receiver_Party_Reference: "party2",
    Payment_Payer_Party_Reference: "party1",
    Cashflow_Sub_State: "Pending Verification",
    Cashflow_Sub_State_Type: "Pending Exception",
    Cashflow_Sub_State_Updater: "123456",
    Status_Event_Type: "",
    Event_Date: "2022-10-20",
  },
  Delivery_Method: "",
  Settlement_Method: "Cash",
  Trade_Id: "1816352",
  Trade_Version: 0,
  Entity: {
    Booking_Entity_SCI_FMID: "10075222",
    Booking_Entity_SCI_FMCODE: null,
    Counterparty_SCI_FMID: "400640613",
    Counterparty_SCI_FMCODE: null,
  },
  Parent_Trade_Id: "1816352",
  Trade_State: "VALIDATED",
  Portfolio: {
    Booking_Entity_Trade_Portfolio_Name: "BCS_FSS_UK_BTBLTQ",
  },
};

export const NotificationCashflow = {
  Cashflow_Id: "008690236385",
  Cashflow_Business_Version: 0,
  Cashflow_Version: 0,
  Cashflow_Minor_Version: 4,
  Cashflow_State: "WAITING",
  Cashflow: {
    Cashflow: {
      Cashflow_Id: "008690236385",
      Cashflow_State: "WAITING",
      Cashflow_Business_Version: 0,
      Cashflow_Version: 0,
      Cashflow_Minor_Version: 4,
    },
  },
  Event_Action: "CASHFLOW_UPDATE",
};

export const CcilNettingCashflow1 = {
  BCS_Trade_Id: "1816352",
  BCS_Parent_Trade_Id: "1816352",
  FMO_Comments: null,
  Cashflow: {
    Cashflow_Id: "008690236385",
    Cashflow_Business_Version: 0,
    Cashflow_Version: 0,
    Cashflow_State: "WAITING",
    Cashflow_Affirmation_Status: "affirmed",
    Cashflow_Event_Type: "New",
    Cashflow_Minor_Version: 4,
    Payment_Currency: "USD",
    Payment_Date: "2022-03-11",
    Payment_Type: "netAmount",
    Payment_Cutoff_Time: "2022-03-10T00:00",
    Pay_Receive_Indicator: "Pay",
    Payment_Amount: "1000",
    Netting_Id: "",
    Netting_Cuttoff_Date: "null",
    Payment_Receiver_Party_Reference: "party2",
    Payment_Payer_Party_Reference: "party1",
    Cashflow_Sub_State: "Pending Verification",
    Cashflow_Sub_State_Type: "Pending Netting",
    Cashflow_Sub_State_Updater: "1470797",
    Status_Event_Type: "",
    Event_Date: "2022-10-20",
  },
  Delivery_Method: "",
  Settlement_Method: "CCIL",
  Trade_Id: "1816352",
  Trade_Version: 0,
  Entity: {
    Booking_Entity_SCI_FMID: "10075222",
    Booking_Entity_SCI_FMCODE: null,
    Counterparty_SCI_FMID: "400640613",
    Counterparty_SCI_FMCODE: null,
  },
  Parent_Trade_Id: "1816352",
  Trade_State: "VALIDATED",
  Portfolio: {
    Booking_Entity_Trade_Portfolio_Name: "BCS_FSS_UK_BTBLTQ",
  },
};

export const CcilNettingCashflow2 = {
  BCS_Trade_Id: "1816352",
  BCS_Parent_Trade_Id: "1816352",
  FMO_Comments: null,
  Cashflow: {
    Cashflow_Id: "008690236385",
    Cashflow_Business_Version: 0,
    Cashflow_Version: 0,
    Cashflow_State: "WAITING",
    Cashflow_Affirmation_Status: "affirmed",
    Cashflow_Event_Type: "New",
    Cashflow_Minor_Version: 4,
    Payment_Currency: "USD",
    Payment_Date: "2022-03-11",
    Payment_Type: "netAmount",
    Payment_Cutoff_Time: "2022-03-10T00:00",
    Pay_Receive_Indicator: "Pay",
    Payment_Amount: "1000",
    Netting_Id: "",
    Netting_Cuttoff_Date: "null",
    Payment_Receiver_Party_Reference: "party2",
    Payment_Payer_Party_Reference: "party1",
    Cashflow_Sub_State: "Pending Verification",
    Cashflow_Sub_State_Type: "Pending Netting",
    Cashflow_Sub_State_Updater: "1470797",
    Status_Event_Type: "",
    Event_Date: "2022-10-20",
  },
  Delivery_Method: "",
  Settlement_Method: "CCIL",
  Trade_Id: "1816352",
  Trade_Version: 0,
  Entity: {
    Booking_Entity_SCI_FMID: "10075222",
    Booking_Entity_SCI_FMCODE: null,
    Counterparty_SCI_FMID: "400640613",
    Counterparty_SCI_FMCODE: null,
  },
  Parent_Trade_Id: "1816352",
  Trade_State: "VALIDATED",
  Portfolio: {
    Booking_Entity_Trade_Portfolio_Name: "BCS_FSS_UK_BTBLTQ",
  },
};

export const mockCashflow2 = {
  BCS_Trade_Id: "1816352",
  BCS_Parent_Trade_Id: "1816352",
  FMO_Comments: null,
  Cashflow: {
    Cashflow_Id: "M08690236385",
    Cashflow_Business_Version: 0,
    Cashflow_Version: 0,
    Cashflow_State: "READY",
    Cashflow_Affirmation_Status: "affirmed",
    Cashflow_Event_Type: "New",
    Cashflow_Minor_Version: 4,
    Payment_Currency: "SGD",
    Payment_Date: "2022-06-17",
    Payment_Type: "netAmount",
    Payment_Cutoff_Time: "2022-03-10T00:00",
    Pay_Receive_Indicator: "Pay",
    Payment_Amount: "1000",
    Netting_Id: "N0000001234",
    Netting_Cuttoff_Date: "null",
    Payment_Receiver_Party_Reference: "party2",
    Payment_Payer_Party_Reference: "party1",
    Cashflow_Sub_State: "Pending Verification",
    Cashflow_Sub_State_Type: "Auto Netting",
    Cashflow_Sub_State_Updater: "1470797",
    Status_Event_Type: "",
    Event_Date: "2022-10-20",
  },
  Delivery_Method: "GROSS",
  Settlement_Method: "Cash",
  Trade_Id: "1816352",
  Trade_Version: 0,
  Entity: {
    Booking_Entity_SCI_FMID: "40075222",
    Booking_Entity_SCI_FMCODE: null,
    Counterparty_SCI_FMID: "100640613",
    Counterparty_SCI_FMCODE: null,
  },
  Parent_Trade_Id: "1816352",
  Trade_State: "VALIDATED",
  Portfolio: {
    Booking_Entity_Trade_Portfolio_Name: "BCS_FSS_UK_BTBLTQ",
  },
};

export const mockCashflow3 = {
  BCS_Trade_Id: "1816352",
  BCS_Parent_Trade_Id: "1816352",
  FMO_Comments: null,
  Cashflow: {
    Cashflow_Id: "008690236386",
    Cashflow_Business_Version: 0,
    Cashflow_Version: 0,
    Cashflow_State: "WAITING",
    Cashflow_Affirmation_Status: "affirmed",
    Cashflow_Event_Type: "New",
    Cashflow_Minor_Version: 4,
    Payment_Currency: "USD",
    Payment_Date: "2022-03-11",
    Payment_Type: "netAmount",
    Payment_Cutoff_Time: "2022-03-10T00:00",
    Pay_Receive_Indicator: "Pay",
    Payment_Amount: "1000",
    Netting_Id: "",
    Netting_Cuttoff_Date: "null",
    Payment_Receiver_Party_Reference: "party2",
    Payment_Payer_Party_Reference: "party1",
    Cashflow_Sub_State: "Pending Verification",
    Cashflow_Sub_State_Type: "Pending Exception",
    Cashflow_Sub_State_Updater: "1470797",
    Status_Event_Type: "",
    Event_Date: "2022-10-20",
  },
  Delivery_Method: "",
  Settlement_Method: "Cash",
  Trade_Id: "1816352",
  Trade_Version: 0,
  Entity: {
    Booking_Entity_SCI_FMID: "10075222",
    Booking_Entity_SCI_FMCODE: null,
    Counterparty_SCI_FMID: "400640613",
    Counterparty_SCI_FMCODE: null,
  },
  Parent_Trade_Id: "1816352",
  Trade_State: "VALIDATED",
  Portfolio: {
    Booking_Entity_Trade_Portfolio_Name: "BCS_FSS_UK_BTBLTQ",
  },
};

export const mockCashflow4LoanIQ = {
  BCS_Trade_Id: "1816352",
  BCS_Parent_Trade_Id: "1816352",
  FMO_Comments: null,
  Cashflow: {
    Cashflow_Id: "008690236385",
    Cashflow_Business_Version: 0,
    Cashflow_Version: 0,
    Cashflow_State: "WAITING",
    Cashflow_Affirmation_Status: "affirmed",
    Cashflow_Event_Type: "New",
    Cashflow_Minor_Version: 4,
    Payment_Currency: "USD",
    Payment_Date: "2022-03-11",
    Payment_Type: "netAmount",
    Payment_Cutoff_Time: "2022-03-10T00:00",
    Pay_Receive_Indicator: "Pay",
    Payment_Amount: "1000",
    Netting_Id: "",
    Netting_Cuttoff_Date: "null",
    Payment_Receiver_Party_Reference: "party2",
    Payment_Payer_Party_Reference: "party1",
    Cashflow_Sub_State: "Pending Verification",
    Cashflow_Sub_State_Type: "Pending Netting",
    Cashflow_Sub_State_Updater: "1470797",
    Status_Event_Type: "",
    Event_Date: "2022-10-20",
  },
  Delivery_Method: "",
  Settlement_Method: "CCIL",
  Trade_Id: "1816352",
  Trade_Version: 0,
  Entity: {
    Booking_Entity_SCI_FMID: "10075222",
    Booking_Entity_SCI_FMCODE: null,
    Counterparty_SCI_FMID: "400640613",
    Counterparty_SCI_FMCODE: null,
  },
  Parent_Trade_Id: "1816352",
  Trade_State: "VALIDATED",
  Portfolio: {
    Booking_Entity_Trade_Portfolio_Name: "BCS_FSS_UK_BTBLTQ",
  },
  Trade_Original_Source_System_Name: "LOANIQ",
};

export const mockCashflow5LoanIQ = {
  BCS_Trade_Id: "1816352",
  BCS_Parent_Trade_Id: "1816352",
  FMO_Comments: null,
  Cashflow: {
    Cashflow_Id: "M08690236385",
    Cashflow_Business_Version: 0,
    Cashflow_Version: 0,
    Cashflow_State: "READY",
    Cashflow_Affirmation_Status: "affirmed",
    Cashflow_Event_Type: "New",
    Cashflow_Minor_Version: 4,
    Payment_Currency: "SGD",
    Payment_Date: "2022-06-17",
    Payment_Type: "netAmount",
    Payment_Cutoff_Time: "2022-03-10T00:00",
    Pay_Receive_Indicator: "Pay",
    Payment_Amount: "1000",
    Netting_Id: "N0000001234",
    Netting_Cuttoff_Date: "null",
    Payment_Receiver_Party_Reference: "party2",
    Payment_Payer_Party_Reference: "party1",
    Cashflow_Sub_State: "Pending Verification",
    Cashflow_Sub_State_Type: "Auto Netting",
    Cashflow_Sub_State_Updater: "1470797",
    Status_Event_Type: "",
    Event_Date: "2022-10-20",
  },
  Delivery_Method: "GROSS",
  Settlement_Method: "Cash",
  Trade_Id: "1816352",
  Trade_Version: 0,
  Entity: {
    Booking_Entity_SCI_FMID: "40075222",
    Booking_Entity_SCI_FMCODE: null,
    Counterparty_SCI_FMID: "100640613",
    Counterparty_SCI_FMCODE: null,
  },
  Parent_Trade_Id: "1816352",
  Trade_State: "VALIDATED",
  Portfolio: {
    Booking_Entity_Trade_Portfolio_Name: "BCS_FSS_UK_BTBLTQ",
  },
  Trade_Original_Source_System_Name: "LOANIQ",
};
