#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
MODE=interactive
INPUT_PATH=""
OUTPUT_ROOT="$SCRIPT_DIR/generated"

usage() {
  cat <<'EOF'
SCB Next tenant onboarding processor

Usage:
  tenant-onboarding.sh
  tenant-onboarding.sh --non-interactive --input <tenant.env> --output-dir <directory>
  tenant-onboarding.sh --help

Interactive mode walks through eight front-to-back onboarding stages.
Non-interactive mode validates an existing input file and generates the same
tenant descriptor, rerunnable environment file, and approval checklist.

Options:
  --non-interactive  Generate without prompts.
  --input PATH       Read public onboarding values and secret references from PATH.
  --output-dir PATH  Write the tenant bundle beneath PATH/<tenant-id>/.
  --help             Show this help without writing files.

This processor never applies Kubernetes resources or accepts raw credentials.
EOF
}

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  usage
  exit 0
fi

fail() {
  printf 'Error: %s\n' "$1" >&2
  exit 1
}

is_known_key() {
  case "$1" in
    TENANT_ID | TENANT_DISPLAY_NAME | BUSINESS_OWNER | TECHNICAL_OWNER | SUPPORT_CONTACT | \
      TARGET_ENVIRONMENT | ISOLATION_MODEL | NAMESPACE | API_PATH | STATIC_PATH | REMOTE_NAME | \
      REMOTE_ENTRY | UI_IMAGE | API_IMAGE | API_SERVICE | WEBSOCKET_PATH | IDENTITY_GROUPS | \
      ENTITLEMENT_PREFIX | SECRET_REFERENCES | DATA_CLASSIFICATION | DATA_STORES | \
      EXTERNAL_EGRESS | AVAILABILITY_SLO | RTO | RPO | ON_CALL)
      return 0
      ;;
    *) return 1 ;;
  esac
}

looks_like_secret_key() {
  [[ "$1" =~ (PASSWORD|TOKEN|PRIVATE_KEY|ACCESS_KEY|CLIENT_SECRET|API_KEY|SECRET_KEY) ]]
}

looks_like_secret_value() {
  local value="$1"
  [[ "$value" == *"-----BEGIN "*"PRIVATE KEY-----"* ]] ||
    [[ "$value" =~ [Bb]earer[[:space:]]+[A-Za-z0-9._-]+ ]] ||
    [[ "$value" =~ AKIA[0-9A-Z]{16} ]] ||
    [[ "$value" =~ ([Pp][Aa][Ss][Ss][Ww][Oo][Rr][Dd]|[Tt][Oo][Kk][Ee][Nn]|[Cc][Ll][Ii][Ee][Nn][Tt]_[Ss][Ee][Cc][Rr][Ee][Tt])[=] ]]
}

load_input() {
  local line key value
  [[ -f "$INPUT_PATH" ]] || fail "Input file does not exist: $INPUT_PATH"

  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ -z "$line" || "$line" == \#* ]] && continue
    [[ "$line" == *=* ]] || fail "Input lines must use KEY=VALUE format."
    key=${line%%=*}
    value=${line#*=}
    [[ "$key" =~ ^[A-Z][A-Z0-9_]*$ ]] || fail "Input contains an invalid field name."
    if looks_like_secret_key "$key" && [[ "$key" != "SECRET_REFERENCES" ]]; then
      fail "Raw secret material is not accepted; provide an approved secret-provider reference instead."
    fi
    is_known_key "$key" || fail "Input contains an unsupported field: $key"
    looks_like_secret_value "$value" &&
      fail "Raw secret material is not accepted; provide an approved secret-provider reference instead."
    printf -v "$key" '%s' "$value"
  done < "$INPUT_PATH"
}

require_value() {
  local key="$1"
  [[ -n "${!key:-}" ]] || fail "$key is required."
}

validate_path() {
  local key="$1" expected="$2" value="${!1:-}"
  [[ "$value" == "$expected" ]] || fail "$key must be $expected"
}

validate_inputs() {
  local key
  for key in \
    TENANT_ID TENANT_DISPLAY_NAME BUSINESS_OWNER TECHNICAL_OWNER SUPPORT_CONTACT \
    TARGET_ENVIRONMENT ISOLATION_MODEL NAMESPACE API_PATH STATIC_PATH REMOTE_NAME REMOTE_ENTRY \
    UI_IMAGE API_IMAGE API_SERVICE IDENTITY_GROUPS ENTITLEMENT_PREFIX SECRET_REFERENCES \
    DATA_CLASSIFICATION DATA_STORES EXTERNAL_EGRESS AVAILABILITY_SLO RTO RPO ON_CALL; do
    require_value "$key"
  done

  [[ ${#TENANT_ID} -le 63 && "$TENANT_ID" =~ ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$ ]] ||
    fail "TENANT_ID must be a lowercase Kubernetes-safe identifier of at most 63 characters."
  [[ ${#NAMESPACE} -le 63 && "$NAMESPACE" =~ ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$ ]] ||
    fail "NAMESPACE must be a lowercase Kubernetes-safe identifier of at most 63 characters."
  case "$TARGET_ENVIRONMENT" in
    development | non-production | production) ;;
    *) fail "TARGET_ENVIRONMENT must be development, non-production, or production." ;;
  esac
  case "$ISOLATION_MODEL" in
    namespace-per-tenant | shared-namespace | dedicated-cluster) ;;
    *) fail "ISOLATION_MODEL must be namespace-per-tenant, shared-namespace, or dedicated-cluster." ;;
  esac
  validate_path API_PATH "/api/$TENANT_ID/"
  validate_path STATIC_PATH "/static/$TENANT_ID/"
  validate_path REMOTE_ENTRY "/static/$TENANT_ID/remoteEntry.js"
  [[ -z "${WEBSOCKET_PATH:-}" || "$WEBSOCKET_PATH" == "$API_PATH"* ]] ||
    fail "WEBSOCKET_PATH must be empty or remain inside $API_PATH"
  [[ "$UI_IMAGE" =~ @sha256:[0-9a-f]{64}$ ]] || fail "UI_IMAGE must use an immutable sha256 digest."
  [[ "$API_IMAGE" =~ @sha256:[0-9a-f]{64}$ ]] || fail "API_IMAGE must use an immutable sha256 digest."
  [[ "$SECRET_REFERENCES" == "none" || "$SECRET_REFERENCES" =~ ^(vault:|externalsecret:|csi:) ]] ||
    fail "SECRET_REFERENCES must be none or use an approved provider prefix."

  for key in TENANT_DISPLAY_NAME BUSINESS_OWNER TECHNICAL_OWNER SUPPORT_CONTACT REMOTE_NAME \
    API_SERVICE IDENTITY_GROUPS ENTITLEMENT_PREFIX SECRET_REFERENCES DATA_CLASSIFICATION DATA_STORES \
    EXTERNAL_EGRESS AVAILABILITY_SLO RTO RPO ON_CALL; do
    looks_like_secret_value "${!key}" &&
      fail "Raw secret material is not accepted; provide an approved secret-provider reference instead."
  done
  return 0
}

yaml_quote() {
  local value="$1"
  value=${value//\'/\'\'}
  printf "'%s'" "$value"
}

render_environment() {
  cat <<EOF
TENANT_ID=$TENANT_ID
TENANT_DISPLAY_NAME=$TENANT_DISPLAY_NAME
BUSINESS_OWNER=$BUSINESS_OWNER
TECHNICAL_OWNER=$TECHNICAL_OWNER
SUPPORT_CONTACT=$SUPPORT_CONTACT
TARGET_ENVIRONMENT=$TARGET_ENVIRONMENT
ISOLATION_MODEL=$ISOLATION_MODEL
NAMESPACE=$NAMESPACE
API_PATH=$API_PATH
STATIC_PATH=$STATIC_PATH
REMOTE_NAME=$REMOTE_NAME
REMOTE_ENTRY=$REMOTE_ENTRY
UI_IMAGE=$UI_IMAGE
API_IMAGE=$API_IMAGE
API_SERVICE=$API_SERVICE
WEBSOCKET_PATH=${WEBSOCKET_PATH:-}
IDENTITY_GROUPS=$IDENTITY_GROUPS
ENTITLEMENT_PREFIX=$ENTITLEMENT_PREFIX
SECRET_REFERENCES=$SECRET_REFERENCES
DATA_CLASSIFICATION=$DATA_CLASSIFICATION
DATA_STORES=$DATA_STORES
EXTERNAL_EGRESS=$EXTERNAL_EGRESS
AVAILABILITY_SLO=$AVAILABILITY_SLO
RTO=$RTO
RPO=$RPO
ON_CALL=$ON_CALL
EOF
}

render_descriptor() {
  cat <<EOF
apiVersion: onboarding.scb-next.io/v1alpha1
kind: PortalTenant
metadata:
  id: $(yaml_quote "$TENANT_ID")
  displayName: $(yaml_quote "$TENANT_DISPLAY_NAME")
  targetEnvironment: $(yaml_quote "$TARGET_ENVIRONMENT")
ownership:
  businessOwner: $(yaml_quote "$BUSINESS_OWNER")
  technicalOwner: $(yaml_quote "$TECHNICAL_OWNER")
  supportContact: $(yaml_quote "$SUPPORT_CONTACT")
  onCall: $(yaml_quote "$ON_CALL")
kubernetes:
  isolationModel: $(yaml_quote "$ISOLATION_MODEL")
  namespace: $(yaml_quote "$NAMESPACE")
portal:
  apiPath: $(yaml_quote "$API_PATH")
  staticPath: $(yaml_quote "$STATIC_PATH")
  remoteName: $(yaml_quote "$REMOTE_NAME")
  remoteEntry: $(yaml_quote "$REMOTE_ENTRY")
workloads:
  uiImage: $(yaml_quote "$UI_IMAGE")
  apiImage: $(yaml_quote "$API_IMAGE")
  apiService: $(yaml_quote "$API_SERVICE")
  websocketPath: $(yaml_quote "${WEBSOCKET_PATH:-}")
security:
  identityGroups: $(yaml_quote "$IDENTITY_GROUPS")
  entitlementPrefix: $(yaml_quote "$ENTITLEMENT_PREFIX")
  secretReferences: $(yaml_quote "$SECRET_REFERENCES")
  dataClassification: $(yaml_quote "$DATA_CLASSIFICATION")
dependencies:
  dataStores: $(yaml_quote "$DATA_STORES")
  externalEgress: $(yaml_quote "$EXTERNAL_EGRESS")
serviceObjectives:
  availability: $(yaml_quote "$AVAILABILITY_SLO")
  rto: $(yaml_quote "$RTO")
  rpo: $(yaml_quote "$RPO")
EOF
}

render_checklist() {
  cat <<EOF
# $TENANT_DISPLAY_NAME onboarding checklist

Tenant ID: \`$TENANT_ID\`<br>
Target environment: \`$TARGET_ENVIRONMENT\`<br>
Descriptor: \`tenant.yaml\`

## 1. Business And Ownership

- [ ] Business capability, users, criticality, and funding are recorded.
- [ ] Business owner, technical owner, support contact, and on-call rotation accept ownership.
- [ ] Data classification, retention, residency, RTO, and RPO are approved.

## 2. Portal Contract

- [ ] The platform team approves \`$API_PATH\` and \`$STATIC_PATH\` as unique path families.
- [ ] Remote \`$REMOTE_NAME\` loads from \`$REMOTE_ENTRY\` through the tenant edge.
- [ ] Navigation, feature flags, identity groups, and \`$ENTITLEMENT_PREFIX\` entitlements are tested.
- [ ] Federation manifests are non-cacheable and immutable assets use approved caching.

## 3. Kubernetes And Workloads

- [ ] Isolation model \`$ISOLATION_MODEL\` and namespace \`$NAMESPACE\` are approved.
- [ ] Tenant edge, UI, API, and optional WebSocket workloads are independently deployable.
- [ ] Services are private ClusterIP and only the platform edge can reach the tenant edge.
- [ ] Images use approved immutable digests, signatures, provenance, SBOMs, and scans.
- [ ] Probes, requests/limits, replicas, topology spread, disruption budgets, and autoscaling are verified.

## 4. Security And Dependencies

- [ ] Workload identity and RBAC follow least privilege with default-deny network policy.
- [ ] Only approved secret-provider references are present; no raw credentials are committed.
- [ ] Positive and negative NetworkPolicy tests pass on the production CNI.
- [ ] Databases, messaging, downstream APIs, DNS, and egress destinations are approved and tested.
- [ ] Authentication, authorization, tenant data segregation, and audit events use real integrations.

## 5. Operations And Activation

- [ ] Logs, metrics, traces, dashboards, alerts, synthetics, and audit retention identify \`$TENANT_ID\`.
- [ ] Load, multi-zone failure, backup/restore, and tenant-edge outage containment are evidenced.
- [ ] Tenant resources are verified directly before platform-edge delegation is enabled.
- [ ] Authenticated browser, API, static asset, WebSocket, and business journeys pass publicly.
- [ ] Rollback removes platform delegation before tenant resources and restores approved versions.
- [ ] Hypercare dates, incident ownership, and steady-state support handoff are recorded.

## 6. Approvals

- [ ] Platform owner approval
- [ ] Tenant owner approval
- [ ] Security approval
- [ ] SRE production-readiness approval
- [ ] Business owner go-live approval

## 7. Offboarding Readiness

- [ ] Data retention/export and audit preservation responsibilities are recorded.
- [ ] Access, identities, secrets, routes, workloads, DNS, alerts, and cost allocation have removal owners.
EOF
}

generate_bundle() {
  local tenant_directory="$OUTPUT_ROOT/$TENANT_ID" temporary_directory
  umask 077
  mkdir -p "$OUTPUT_ROOT"
  temporary_directory=$(mktemp -d "$OUTPUT_ROOT/.${TENANT_ID}.XXXXXX")
  trap 'rm -rf "${temporary_directory:-}"' EXIT
  render_descriptor > "$temporary_directory/tenant.yaml"
  render_environment > "$temporary_directory/tenant.env"
  render_checklist > "$temporary_directory/onboarding-checklist.md"
  mkdir -p "$tenant_directory"
  mv "$temporary_directory/tenant.yaml" "$tenant_directory/tenant.yaml"
  mv "$temporary_directory/tenant.env" "$tenant_directory/tenant.env"
  mv "$temporary_directory/onboarding-checklist.md" "$tenant_directory/onboarding-checklist.md"
  rmdir "$temporary_directory"
  trap - EXIT

  printf 'Generated tenant onboarding bundle: %s\n' "$tenant_directory"
  printf 'Next: review tenant.yaml and complete onboarding-checklist.md before provisioning.\n'
}

capture() {
  local key="$1" prompt="$2"
  ask "$key" "$prompt"
  write_env "$key" "${!key}"
}

run_interactive() {
  if [[ "$ENV_FILE" == ".env" ]]; then
    ENV_FILE="$SCRIPT_DIR/generated/tenant-onboarding.env"
  fi
  mkdir -p "$(dirname "$ENV_FILE")"
  banner "SCB Next tenant onboarding"

  stage "Tenant identity and business ownership"
  say "Use an immutable lowercase tenant ID. Record accountable people, not team aliases alone."
  capture TENANT_ID "Tenant ID (for example alpha-payments):"
  capture TENANT_DISPLAY_NAME "Portal display name:"
  capture BUSINESS_OWNER "Business owner:"
  capture TECHNICAL_OWNER "Technical owner:"
  capture SUPPORT_CONTACT "Support contact or channel:"

  stage "Environment and Kubernetes isolation"
  say "Production normally uses namespace-per-tenant unless governance approves another boundary."
  capture TARGET_ENVIRONMENT "Target environment (development, non-production, production):"
  capture ISOLATION_MODEL "Isolation model (namespace-per-tenant, shared-namespace, dedicated-cluster):"
  capture NAMESPACE "Kubernetes namespace:"

  stage "Portal routes and frontend composition"
  say "The platform edge delegates only these public path families; tenant internals stay hidden."
  capture API_PATH "API path (must be /api/<tenant-id>/):"
  capture STATIC_PATH "Static path (must be /static/<tenant-id>/):"
  capture REMOTE_NAME "Module Federation remote name:"
  capture REMOTE_ENTRY "Remote entry path:"

  stage "Frontend and backend workloads"
  say "Use registry images pinned by sha256 digest. Leave WebSocket path empty when unused."
  capture UI_IMAGE "Frontend image with @sha256 digest:"
  capture API_IMAGE "Backend image with @sha256 digest:"
  capture API_SERVICE "Backend Kubernetes Service name:"
  capture WEBSOCKET_PATH "WebSocket path (optional):"

  stage "Identity, entitlements, and secret references"
  warn "Do not paste credentials. Use only vault:, externalsecret:, csi:, or none."
  capture IDENTITY_GROUPS "Identity groups (comma-separated):"
  capture ENTITLEMENT_PREFIX "Entitlement prefix:"
  capture SECRET_REFERENCES "Approved secret-provider references:"

  stage "Data and external dependencies"
  capture DATA_CLASSIFICATION "Data classification:"
  capture DATA_STORES "Data stores (comma-separated):"
  capture EXTERNAL_EGRESS "Approved egress destinations (comma-separated):"

  stage "Service objectives and operations"
  capture AVAILABILITY_SLO "Availability SLO:"
  capture RTO "Recovery time objective:"
  capture RPO "Recovery point objective:"
  capture ON_CALL "On-call rotation:"

  stage "Review and generate"
  say "The processor will validate and generate local review artifacts only."
  validate_inputs
  confirm "Generate the tenant onboarding bundle?" || fail "Generation cancelled."
  generate_bundle
  finish
}

while (( $# > 0 )); do
  case "$1" in
    --non-interactive)
      MODE=non-interactive
      shift
      ;;
    --input)
      (( $# >= 2 )) || fail "--input requires a path."
      INPUT_PATH="$2"
      shift 2
      ;;
    --output-dir)
      (( $# >= 2 )) || fail "--output-dir requires a path."
      OUTPUT_ROOT="$2"
      shift 2
      ;;
    --help | -h)
      usage
      exit 0
      ;;
    *) fail "Unknown option: $1" ;;
  esac
done

if [[ "$MODE" == "non-interactive" ]]; then
  [[ -n "$INPUT_PATH" ]] || fail "--input is required with --non-interactive."
  load_input
  validate_inputs
  generate_bundle
else
  [[ -z "$INPUT_PATH" ]] || fail "--input requires --non-interactive."
  run_interactive
fi
