export const fontSize = [
  { name: 'Title 1', value: 'h1', className: 'h1' },
  { name: 'Title 2', value: 'h2', className: 'h2' },
  { name: 'Title 3', value: 'h3', className: 'h3' },
  { name: 'Title 4', value: 'h4', className: 'h4' },
  { name: 'Title 5', value: 'h5', className: 'h5' },
  { name: 'Title 6', value: 'h6', className: 'h6' },
  { name: 'Body 1', value: 'div', className: 'div' },
  { name: 'Body 2', value: 'p', className: 'p' },
  { name: 'Body 3', value: 'aside', className: 'aside' },
  { name: 'Body 4', value: 'section', className: 'section' },
];

export const fontTextColor = [
  { name: 'Black', value: '#000000' },
  { name: 'Primary', value: '#00172E' },
  { name: 'Secondary', value: '#595959' },
  { name: 'Tertiary', value: '#999999' },
  { name: 'White', value: '#FFFFFF' },
  { name: 'Blue', value: '#0473EA' },
  { name: 'Green', value: '#38D200' },
  { name: 'Amber', value: '#FAAD14' },
  { name: 'Red', value: '#E00A15' },
  
];
export const fontBackColor = [
  { name: 'No Color', value: '#fefefe' },
  { name: 'Amber', value: '#FDE6B8' },
  { name: 'Red', value: '#F6B5B8' },
  { name: 'Blue', value: '#B3D5F8' },
  { name: 'Green', value: '#C3F3B4' },
  { name: 'Grey', value: '#D9D9D9' },
  { name: 'White', value: '#FFFFFF' },
];

export enum EMODIFIER {
  CTRL = 'CTRL',
  SHIFT = 'SHIFT',
  CMD = 'CMD',
  TAB = 'TAB',
}

export enum EKEY_MAP {
  BACKSPACE = 8,
  TAB = 9,
  ENTER = 13,
  ESCAPE = 27,
  SPACE = 32,
  DELETE = 46,

  // Arrow
  LEFT = 37,
  UP = 38,
  RIGHT = 39,
  DOWN = 40,

  // Number: 0-9
  NUM0 = 48,
  NUM1 = 49,
  NUM2 = 50,
  NUM3 = 51,
  NUM4 = 52,
  NUM5 = 53,
  NUM6 = 54,
  NUM7 = 55,
  NUM8 = 56,

  // Alphabet: a-z
  A = 65,
  B = 66,
  E = 69,
  I = 73,
  J = 74,
  K = 75,
  L = 76,
  M = 77,
  Q = 81,
  R = 82,
  S = 83,
  U = 85,
  V = 86,
  Y = 89,
  Z = 90,

  SLASH = 191,
  LEFTBRACKET = 219,
  BACKSLASH = 220,
  RIGHTBRACKET = 221,

  // Navigation
  HOME = 36,
  END = 35,
  PAGEUP = 33,
  PAGEDOWN = 34,
}

export enum ENODE_TYPE {
  ELEMENT_NODE = 1,
  ATTRIBUTE_NODE,
  TEXT_NODE,
  CDATA_SECTION_NODE,
  ENTITY_REFERENCE_NODE,
  ENTITY_NODE,
  PROCESSING_INSTRUCTION_NODE,
  COMMENT_NODE,
  DOCUMENT_NODE,
  DOCUMENT_TYPE_NODE,
  DOCUMENT_FRAGMENT_NODE,
  NOTATION_NODE,
}

const { CTRL, CMD, SHIFT, TAB } = EMODIFIER;
const {
  NUM0,
  NUM1,
  NUM2,
  NUM3,
  NUM4,
  NUM5,
  NUM6,
  A,
  UP,
  DOWN,
  NUM7,
  NUM8,
  LEFTBRACKET,
  RIGHTBRACKET,
  Z,
  Y,
  B,
  I,
  U,
  S,
  L,
  M,
  E,
  R,
  Q,
  BACKSLASH,
  BACKSPACE,
} = EKEY_MAP;

export const KEY_MAP = {
  pc: {
    [EKEY_MAP[BACKSPACE]]: 'backspace',
    [TAB]: 'tab',
    [`${CTRL}+${EKEY_MAP[Z]}`]: 'undo',
    [`${CTRL}+${EKEY_MAP[Y]}`]: 'redo',
    [`${CTRL}+${EKEY_MAP[B]}`]: 'bold',
    [`${CTRL}+${EKEY_MAP[I]}`]: 'italic',
    [`${CTRL}+${EKEY_MAP[U]}`]: 'underline',
    [`${CTRL}+${SHIFT}+${EKEY_MAP[S]}`]: 'strikeThrough',
    [`${CTRL}+${EKEY_MAP[BACKSLASH]}`]: 'removeFormat',
    [`${CTRL}+${SHIFT}+${EKEY_MAP[L]}`]: 'justifyLeft',
    [`${CTRL}+${SHIFT}+${EKEY_MAP[E]}`]: 'justifyCenter',
    [`${CTRL}+${SHIFT}+${EKEY_MAP[R]}`]: 'justifyRight',
    [`${CTRL}+${SHIFT}+${EKEY_MAP[NUM7]}`]: 'insertUnorderedList',
    [`${CTRL}+${SHIFT}+${EKEY_MAP[NUM8]}`]: 'insertOrderedList',
    [`${CTRL}+${EKEY_MAP[LEFTBRACKET]}`]: 'outdent',
    [`${CTRL}+${EKEY_MAP[RIGHTBRACKET]}`]: 'indent',
    [`${CTRL}+${EKEY_MAP[NUM0]}`]: 'formatPara',
    [`${CTRL}+${EKEY_MAP[NUM1]}`]: 'formatH1',
    [`${CTRL}+${EKEY_MAP[NUM2]}`]: 'formatH2',
    [`${CTRL}+${EKEY_MAP[NUM3]}`]: 'formatH3',
    [`${CTRL}+${EKEY_MAP[NUM4]}`]: 'formatH4',
    [`${CTRL}+${EKEY_MAP[NUM5]}`]: 'formatH5',
    [`${CTRL}+${EKEY_MAP[NUM6]}`]: 'formatH6',
    [`${CTRL}+${EKEY_MAP[A]}`]: 'selectAll',
    [`${CTRL}+${SHIFT}+${EKEY_MAP[UP]}`]: 'superscript',
    [`${CTRL}+${SHIFT}+${EKEY_MAP[DOWN]}`]: 'subscript',
    [`${CTRL}+${SHIFT}+${EKEY_MAP[Q]}`]: 'formatBlockquote',
    [`${CTRL}+${SHIFT}+${EKEY_MAP[M]}`]: 'insertImage',
  },

  mac: {
    [EKEY_MAP[BACKSPACE]]: 'backspace',
    [TAB]: 'tab',
    [`${CMD}+${EKEY_MAP[Z]}`]: 'undo',
    [`${CMD}+${SHIFT}+${EKEY_MAP[Z]}`]: 'redo',
    [`${CMD}+${EKEY_MAP[B]}`]: 'bold',
    [`${CMD}+${EKEY_MAP[I]}`]: 'italic',
    [`${CMD}+${EKEY_MAP[U]}`]: 'underline',
    [`${CMD}+${SHIFT}+${EKEY_MAP[S]}`]: 'strikeThrough',
    [`${CMD}+${EKEY_MAP[BACKSLASH]}`]: 'removeFormat',
    [`${CMD}+${SHIFT}+${EKEY_MAP[L]}`]: 'justifyLeft',
    [`${CMD}+${SHIFT}+${EKEY_MAP[E]}`]: 'justifyCenter',
    [`${CMD}+${SHIFT}+${EKEY_MAP[R]}`]: 'justifyRight',
    [`${CMD}+${SHIFT}+${EKEY_MAP[NUM7]}`]: 'insertUnorderedList',
    [`${CMD}+${SHIFT}+${EKEY_MAP[NUM8]}`]: 'insertOrderedList',
    [`${CMD}+${EKEY_MAP[LEFTBRACKET]}`]: 'outdent',
    [`${CMD}+${EKEY_MAP[RIGHTBRACKET]}`]: 'indent',
    [`${CMD}+${EKEY_MAP[NUM0]}`]: 'formatPara',
    [`${CMD}+${EKEY_MAP[NUM1]}`]: 'formatH1',
    [`${CMD}+${EKEY_MAP[NUM2]}`]: 'formatH2',
    [`${CMD}+${EKEY_MAP[NUM3]}`]: 'formatH3',
    [`${CMD}+${EKEY_MAP[NUM4]}`]: 'formatH4',
    [`${CMD}+${EKEY_MAP[NUM5]}`]: 'formatH5',
    [`${CMD}+${EKEY_MAP[NUM6]}`]: 'formatH6',
    [`${CMD}+${EKEY_MAP[A]}`]: 'selectAll',
    [`${CMD}+${SHIFT}+${EKEY_MAP[UP]}`]: 'superscript',
    [`${CMD}+${SHIFT}+${EKEY_MAP[DOWN]}`]: 'subscript',
    [`${CMD}+${SHIFT}+${EKEY_MAP[Q]}`]: 'formatBlockquote',
    [`${CMD}+${SHIFT}+${EKEY_MAP[M]}`]: 'insertImage',
  },
};

export const MAPPING_TOOLBAR_COMMAND = {
  undo: KEY_MAP.pc[`${CTRL}+${EKEY_MAP[Z]}`],
  redo: KEY_MAP.pc[`${CTRL}+${EKEY_MAP[Y]}`],
  fontstyle: [
    KEY_MAP.pc[`${CTRL}+${EKEY_MAP[NUM0]}`],
    KEY_MAP.pc[`${CTRL}+${EKEY_MAP[NUM1]}`],
    KEY_MAP.pc[`${CTRL}+${EKEY_MAP[NUM2]}`],
    KEY_MAP.pc[`${CTRL}+${EKEY_MAP[NUM3]}`],
    KEY_MAP.pc[`${CTRL}+${EKEY_MAP[NUM4]}`],
    KEY_MAP.pc[`${CTRL}+${EKEY_MAP[NUM5]}`],
    KEY_MAP.pc[`${CTRL}+${EKEY_MAP[NUM6]}`],
  ],
  bold: KEY_MAP.pc[`${CTRL}+${EKEY_MAP[B]}`],
  italic: KEY_MAP.pc[`${CTRL}+${EKEY_MAP[I]}`],
  underline: KEY_MAP.pc[`${CTRL}+${EKEY_MAP[U]}`],
  strikethrough: KEY_MAP.pc[`${CTRL}+${SHIFT}+${EKEY_MAP[S]}`],
  subscript: KEY_MAP.pc[`${CTRL}+${SHIFT}+${EKEY_MAP[UP]}`],
  superscript: KEY_MAP.pc[`${CTRL}+${SHIFT}+${EKEY_MAP[DOWN]}`],
  clear: KEY_MAP.pc[`${CTRL}+${EKEY_MAP[BACKSLASH]}`],
  alignleft: KEY_MAP.pc[`${CTRL}+${SHIFT}+${EKEY_MAP[L]}`],
  aligncenter: KEY_MAP.pc[`${CTRL}+${SHIFT}+${EKEY_MAP[E]}`],
  alignright: KEY_MAP.pc[`${CTRL}+${SHIFT}+${EKEY_MAP[R]}`],
  orderedlist: KEY_MAP.pc[`${CTRL}+${SHIFT}+${EKEY_MAP[NUM8]}`],
  unorderedlist: KEY_MAP.pc[`${CTRL}+${SHIFT}+${EKEY_MAP[NUM7]}`],
  outdent: KEY_MAP.pc[`${CTRL}+${EKEY_MAP[LEFTBRACKET]}`],
  indent: KEY_MAP.pc[`${CTRL}+${EKEY_MAP[RIGHTBRACKET]}`],
  quote: KEY_MAP.pc[`${CTRL}+${SHIFT}+${EKEY_MAP[Q]}`],
  tab: KEY_MAP.pc[TAB],
  insertimage: KEY_MAP.pc[`${CTRL}+${SHIFT}+${EKEY_MAP[M]}`],
};

export const MARKS = {
  injectedTablePlaceholder: '[rte-action]injected-table-placeholder',
};

export enum E_OPERATORS {
  'toggle-header',
  'insert-row-above',
  'insert-row-below',
  'delete-row',
  'insert-column-left',
  'insert-column-right',
  'delete-column',
  '10-width' = 10,
  '20-width' = 20,
  '30-width' = 30,
  '40-width' = 40,
  '50-width' = 50,
  '60-width' = 60,
  '70-width' = 70,
  '80-width' = 80,
  '90-width' = 90,
  'auto-size',
}
export const DESCRIPTION_OF_OPERATORS = {
  [E_OPERATORS['toggle-header']]: 'Table Header',
  [E_OPERATORS['insert-row-above']]: 'Insert Row Above',
  [E_OPERATORS['insert-row-below']]: 'Insert Row below',
  [E_OPERATORS['delete-row']]: 'Delete Row',
  [E_OPERATORS['insert-column-left']]: 'Insert Column Left',
  [E_OPERATORS['insert-column-right']]: 'Insert Column Right',
  [E_OPERATORS['delete-column']]: 'Delete Column',
  [E_OPERATORS['10-width']]: '10% width scale',
  [E_OPERATORS['20-width']]: '20% width scale',
  [E_OPERATORS['30-width']]: '30% width scale',
  [E_OPERATORS['40-width']]: '40% width scale',
  [E_OPERATORS['50-width']]: '50% width scale',
  [E_OPERATORS['60-width']]: '60% width scale',
  [E_OPERATORS['70-width']]: '70% width scale',
  [E_OPERATORS['80-width']]: '80% width scale',
  [E_OPERATORS['90-width']]: '90% width scale',
  [E_OPERATORS['auto-size']]: 'Auto scale',
};

export const ICON_OF_OPERATORS = {
  [E_OPERATORS['toggle-header']]: 'table-header',
  [E_OPERATORS['insert-row-above']]: 'insert-row-above',
  [E_OPERATORS['insert-row-below']]: 'insert-row-below',
  [E_OPERATORS['delete-row']]: 'delete-row',
  [E_OPERATORS['insert-column-left']]: 'insert-column-left',
  [E_OPERATORS['insert-column-right']]: 'insert-column-right',
  [E_OPERATORS['delete-column']]: 'delete-column',
  [E_OPERATORS['10-width']]: 'delete-column',
  [E_OPERATORS['20-width']]: 'delete-column',
  [E_OPERATORS['30-width']]: 'delete-column',
  [E_OPERATORS['40-width']]: 'delete-column',
  [E_OPERATORS['50-width']]: 'delete-column',
  [E_OPERATORS['60-width']]: 'delete-column',
  [E_OPERATORS['70-width']]: 'delete-column',
  [E_OPERATORS['80-width']]: 'delete-column',
  [E_OPERATORS['90-width']]: 'delete-column',
  [E_OPERATORS['auto-size']]: 'delete-column',
};

export const ROW_OPERATORS = [
  {
    icon: 'insert-row-above',
    desc: DESCRIPTION_OF_OPERATORS[E_OPERATORS['insert-row-above']],
    actionType: E_OPERATORS['insert-row-above'],
  },
  {
    icon: 'insert-row-below',
    desc: DESCRIPTION_OF_OPERATORS[E_OPERATORS['insert-row-below']],
    actionType: E_OPERATORS['insert-row-below'],
  },
  {
    icon: 'delete-row',
    desc: DESCRIPTION_OF_OPERATORS[E_OPERATORS['delete-row']],
    actionType: E_OPERATORS['delete-row'],
  },
];
export const COLUMN_OPERATORS = [
  {
    icon: 'insert-column-left',
    desc: DESCRIPTION_OF_OPERATORS[E_OPERATORS['insert-column-left']],
    actionType: E_OPERATORS['insert-column-left'],
  },
  {
    icon: 'insert-column-right',
    desc: DESCRIPTION_OF_OPERATORS[E_OPERATORS['insert-column-right']],
    actionType: E_OPERATORS['insert-column-right'],
  },
  {
    icon: 'delete-column',
    desc: DESCRIPTION_OF_OPERATORS[E_OPERATORS['delete-column']],
    actionType: E_OPERATORS['delete-column'],
  },
];
export const SIZE_OPERATORS = [
  {
    icon: 'weight-two',
    desc: DESCRIPTION_OF_OPERATORS[E_OPERATORS['20-width']],
    actionType: E_OPERATORS['20-width'],
  },
  {
    icon: 'weight-four',
    desc: DESCRIPTION_OF_OPERATORS[E_OPERATORS['40-width']],
    actionType: E_OPERATORS['40-width'],
  },
  {
    icon: 'weight-six',
    desc: DESCRIPTION_OF_OPERATORS[E_OPERATORS['60-width']],
    actionType: E_OPERATORS['60-width'],
  },
  {
    icon: 'weight-eight',
    desc: DESCRIPTION_OF_OPERATORS[E_OPERATORS['80-width']],
    actionType: E_OPERATORS['80-width'],
  },
  {
    icon: 'weight-auto',
    desc: DESCRIPTION_OF_OPERATORS[E_OPERATORS['auto-size']],
    actionType: E_OPERATORS['auto-size'],
  },
];

export const aiShortcuts = [
  // { title: 'Ask AI', action: 'ask-ai', prompt: 'Ask AI', selection: true },
  { title: 'Summarize content', prompt: 'Provide the key points and concepts in this content in a succinct summary.', selection: true },
  { title: 'Improve writing', prompt: 'Rewrite this content with no spelling mistakes, proper grammar, and with more descriptive language, using best writing practices without losing the original meaning.', selection: true },
  { title: 'Simplify language', prompt: 'Rewrite this content with simplified language and reduce the complexity of the writing, so that the content is easier to understand.', selection: true },
  { title: 'Expand upon', prompt: 'Expand upon this content with descriptive language and more detailed explanations, to make the writing easier to understand and increase the length of the content.', selection: true },
  { title: 'Trim content', prompt: 'Remove any repetitive, redundant, or non-essential writing in this content without changing the meaning or losing any key information.', selection: true },
  {
    title: 'Change tone', subprompts: [
      { title: 'Professional', prompt: 'Rewrite this content using polished, formal, and respectful language to convey professional expertise and competence.', selection: true },
      { title: 'Casual', prompt: 'Rewrite this content with casual, informal language to convey a casual conversation with a real person.', selection: true },
      { title: 'Direct', prompt: 'Rewrite this content with direct language using only the essential information.', selection: true },
      { title: 'Confident', prompt: 'Rewrite this content using compelling, optimistic language to convey confidence in the writing.', selection: true },
      { title: 'Friendly', prompt: 'Rewrite this content using friendly, comforting language, to convey understanding and empathy.', selection: true },
    ],
  },
  {
    title: 'Change style', subprompts: [
      { title: 'Business', prompt: 'Rewrite this content as a business professional with formal language.', selection: true },
      { title: 'Legal', prompt: 'Rewrite this content as a legal professional using valid legal terminology.', selection: true },
      { title: 'Journalism', prompt: 'Rewrite this content as a journalist using engaging language to convey the importance of the information.', selection: true },
      { title: 'Medical', prompt: 'Rewrite this content as a medical professional using valid medical terminology.', selection: true },
      { title: 'Poetic', prompt: 'Rewrite this content as a poem using poetic techniques without losing the original meaning.', selection: true },
    ],
  },
  {
    title: 'Translate', subprompts: [
      { title: 'Translate to English', prompt: 'Translate this content to English language.', selection: true },
      { title: 'Translate to Spanish', prompt: 'Translate this content to Spanish language.', selection: true },
      { title: 'Translate to Portuguese', prompt: 'Translate this content to Portuguese language.', selection: true },
      { title: 'Translate to German', prompt: 'Translate this content to German language.', selection: true },
      { title: 'Translate to French', prompt: 'Translate this content to French language.', selection: true },
      { title: 'Translate to Norwegian', prompt: 'Translate this content to Norwegian language.', selection: true },
      { title: 'Translate to Ukrainian', prompt: 'Translate this content to Ukrainian language.', selection: true },
      { title: 'Translate to Japanese', prompt: 'Translate this content to Japanese language.', selection: true },
      { title: 'Translate to Korean', prompt: 'Translate this content to Korean language.', selection: true },
      { title: 'Translate to Simplified Chinese', prompt: 'Translate this content to Simplified Chinese language.', selection: true },
      { title: 'Translate to Hebrew', prompt: 'Translate this content to Hebrew language.', selection: true },
      { title: 'Translate to Hindi', prompt: 'Translate this content to Hindi language.', selection: true },
      { title: 'Translate to Arabic', prompt: 'Translate this content to Arabic language.', selection: true },
    ],
  },
];
