/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class", // Enable dark mode via class strategy
  important: ":is(.flowzero-app, .flowzero-portal)",
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  corePlugins: {
    container: false,
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        dark: {
          "container-layer": "#262626",
          "content-title": "#D9D9D9",
          "content-body": "#B2B2B2",
          "content-label-text": "#B2B2B2",
          "divide-base": "#666666",
          "input-text": "#CCCCCC",
          "surface-primary-subtle-hover": "#012E5D",
          "link-primary-default": "#9AC7F6",
          "link-primary-selected": "#E5F1FC",
          "zero-selected": "#00172E",
          "link-secondary-default": "#9AC7F6",
          "secondary-default": "#737373",
          "secondary-disabled": "#333333",
          "secondary-selected": "#0250A3",
          "subtle-pressed": "#023975",
          "placeholder-text": "#999999",
          "border-secondary-hover": "#4F9DF0",
          "link-primary-pressed": "#CCE3FA",
          "solid-disabled": "#0D0D0D",
          bg: "#18181c",
          text: "#e5e7eb",
          primary: "#1f2937",
          secondary: "#374151",
          accent: "#6366f1",
        },
        light: {
          "container-layer": "#FFFFFF",
          "content-title": "#262626",
          "content-body": "#4D4D4D",
          "content-label-text": "#4D4D4D",
          "divide-base": "#CCCCCC",
          "input-text": "#333333",
          "surface-primary-subtle-hover": "#E5F1FC",
          "link-primary-default": "#0473EA",
          "link-primary-selected": "#0250A3",
          "zero-selected": "#E5F1FC",
          "link-secondary-default": "#012246",
          "secondary-default": "#CCCCCC",
          "secondary-disabled": "#CCCCCC",
          "secondary-selected": "#0250A3",
          "subtle-pressed": "#81B9F4",
          "placeholder-text": "#666666",
          "border-secondary-default": "#737373",
          "border-secondary-hover": "#4F9DF0",
          "text-secondary-default": "#00172E",
          "text-secondary-hover": "#0367D2",
          "link-primary-pressed": "#035CBB",
          "solid-disabled": "#E5E5E5",
          bg: "#ffffff",
          text: "#1f2937",
          primary: "#f3f4f6",
          secondary: "#e5e7eb",
          accent: "#6366f1",
        },
      },
    },
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      "lg-xl": "1180px",
      xl: "1400px",
      "2xl": "1600px",
    },
  },
  plugins: [],
};
