/// <reference types="react" />
declare const SearchGrid: import("@emotion/styled").StyledComponent<
  import("@mui/material/Grid").GridOwnProps &
    import("@mui/material/OverridableComponent").CommonProps &
    Omit<
      Omit<
        import("react").DetailedHTMLProps<
          import("react").HTMLAttributes<HTMLDivElement>,
          HTMLDivElement
        >,
        "ref"
      > & {
        ref?:
          | ((instance: HTMLDivElement | null) => void)
          | import("react").RefObject<HTMLDivElement>
          | null
          | undefined;
      },
      | "children"
      | "zIndex"
      | "direction"
      | "spacing"
      | "typography"
      | "fontFamily"
      | "fontSize"
      | "textTransform"
      | "borderRadius"
      | "alignContent"
      | "alignItems"
      | "alignSelf"
      | "bottom"
      | "boxShadow"
      | "boxSizing"
      | "color"
      | "columnGap"
      | "display"
      | "flexBasis"
      | "flexDirection"
      | "flexGrow"
      | "flexShrink"
      | "flexWrap"
      | "fontStyle"
      | "fontWeight"
      | "gridAutoColumns"
      | "gridAutoFlow"
      | "gridAutoRows"
      | "gridTemplateAreas"
      | "gridTemplateColumns"
      | "gridTemplateRows"
      | "height"
      | "justifyContent"
      | "justifyItems"
      | "justifySelf"
      | "left"
      | "letterSpacing"
      | "lineHeight"
      | "marginBlockEnd"
      | "marginBlockStart"
      | "marginBottom"
      | "marginInlineEnd"
      | "marginInlineStart"
      | "marginLeft"
      | "marginRight"
      | "marginTop"
      | "maxHeight"
      | "maxWidth"
      | "minHeight"
      | "minWidth"
      | "order"
      | "paddingBlockEnd"
      | "paddingBlockStart"
      | "paddingBottom"
      | "paddingInlineEnd"
      | "paddingInlineStart"
      | "paddingLeft"
      | "paddingRight"
      | "paddingTop"
      | "position"
      | "right"
      | "rowGap"
      | "textAlign"
      | "textOverflow"
      | "top"
      | "visibility"
      | "whiteSpace"
      | "width"
      | "border"
      | "borderBottom"
      | "borderColor"
      | "borderLeft"
      | "borderRight"
      | "borderTop"
      | "columns"
      | "container"
      | "flex"
      | "gap"
      | "gridArea"
      | "gridColumn"
      | "gridRow"
      | "margin"
      | "marginBlock"
      | "marginInline"
      | "overflow"
      | "padding"
      | "paddingBlock"
      | "paddingInline"
      | "className"
      | "style"
      | "classes"
      | "sx"
      | "p"
      | "bgcolor"
      | "m"
      | "mt"
      | "mr"
      | "mb"
      | "ml"
      | "mx"
      | "marginX"
      | "my"
      | "marginY"
      | "pt"
      | "pr"
      | "pb"
      | "pl"
      | "px"
      | "paddingX"
      | "py"
      | "paddingY"
      | "displayPrint"
      | "wrap"
      | "xs"
      | "sm"
      | "md"
      | "lg"
      | "xl"
      | "columnSpacing"
      | "item"
      | "rowSpacing"
      | "zeroMinWidth"
    > &
    import("@mui/system").MUIStyledCommonProps<
      import("@mui/material/styles").Theme
    >,
  {},
  {}
>;
export default SearchGrid;
