CREATE TABLE IF NOT EXISTS ratan_flowzero_orchestration_service.t_attachments (
    id                  VARCHAR(20)  NOT NULL,
    business_id         VARCHAR(100) NOT NULL,
    file_name           VARCHAR(500) NOT NULL,
    file_size           BIGINT,
    mime_type           VARCHAR(100),
    storage_type        VARCHAR(20)  NOT NULL,
    bucket              VARCHAR(500) NOT NULL DEFAULT '/',
    storage_ref         JSONB,
    status              VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    deleted_by          VARCHAR(100),
    deleted_at          TIMESTAMP,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          VARCHAR(100) NOT NULL,
    updated_by          VARCHAR(100) NOT NULL,
    version             INT          NOT NULL DEFAULT 0,

    CONSTRAINT pk_attachments PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_att_business_id_status
    ON ratan_flowzero_orchestration_service.t_attachments (business_id, status);

CREATE INDEX IF NOT EXISTS idx_att_status_created_at
    ON ratan_flowzero_orchestration_service.t_attachments (status, created_at)
    WHERE status = 'PENDING';


CREATE INDEX IF NOT EXISTS idx_att_storage_ref_gin
    ON ratan_flowzero_orchestration_service.t_attachments USING GIN (storage_ref)
    WHERE storage_ref IS NOT NULL;


-- Table and column comments
COMMENT ON TABLE  ratan_flowzero_orchestration_service.t_attachments                     IS 'Attachment master table: stores file information and lifecycle status for any business entity; storage-backend agnostic (FILENET / MINIO / NAS)';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_attachments.id                  IS 'Primary key (Snowflake ID, generated by the application layer)';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_attachments.business_id         IS 'Generic business entity ID (e.g. Workflow instance ID, order ID); replaces the old workflow_instance_id for broader reuse';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_attachments.file_name           IS 'Original file name';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_attachments.file_size           IS 'File size in bytes';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_attachments.mime_type           IS 'Content-Type, e.g. application/pdf';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_attachments.storage_type        IS 'Storage backend identifier: FILENET | MINIO | NAS';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_attachments.bucket              IS 'Storage directory: MINIO/NAS → actual path; FILENET → fixed "/"';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_attachments.storage_ref         IS 'Storage backend reference (JSONB); structure depends on storage_type. FILENET: {"fileId":"…","docCategory":"…","docType":"…","docName":"…","leid":"…"}. NULL while status=PENDING.';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_attachments.status              IS 'Lifecycle status: PENDING=uploading | ACTIVE=available | DELETED=soft-deleted';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_attachments.deleted_by          IS 'User ID of the person who soft-deleted the file';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_attachments.deleted_at          IS 'Timestamp of the soft-delete operation';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_attachments.created_at          IS 'Record creation timestamp (auto-populated by JPA auditing)';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_attachments.updated_at          IS 'Record last-modified timestamp (auto-populated by JPA auditing)';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_attachments.created_by          IS 'User who created the record (auto-populated from security context)';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_attachments.updated_by          IS 'User who last modified the record (auto-populated from security context)';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_attachments.version             IS 'JPA optimistic-lock version counter';


CREATE TABLE IF NOT EXISTS ratan_flowzero_orchestration_service.t_retry_task (

    id                  VARCHAR(20)  NOT NULL,
    biz_type            VARCHAR(50)  NOT NULL,
    biz_id              VARCHAR(100) NOT NULL,
    payload             JSONB        NOT NULL,
    status              VARCHAR(20)  NOT NULL,
    retry_count         INT          NOT NULL DEFAULT 0,
    max_retry           INT          NOT NULL DEFAULT 3,
    last_error          TEXT,
    next_retry_at       TIMESTAMP,
    synced_at           TIMESTAMP,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          VARCHAR(100) NOT NULL,
    updated_by          VARCHAR(100) NOT NULL,
    version             INT          NOT NULL DEFAULT 0,

    CONSTRAINT pk_retry_task PRIMARY KEY (id),
    CONSTRAINT uq_retry_task_biz_type_id UNIQUE (biz_type, biz_id)
);

CREATE INDEX IF NOT EXISTS idx_rt_suspended_retry
    ON ratan_flowzero_orchestration_service.t_retry_task (biz_type, next_retry_at)
    WHERE status = 'SUSPENDED';

CREATE INDEX IF NOT EXISTS idx_rt_failed_retry
    ON ratan_flowzero_orchestration_service.t_retry_task (biz_type, next_retry_at, retry_count)
    WHERE status = 'FAILED';

CREATE INDEX IF NOT EXISTS idx_rt_biz_id_type
    ON ratan_flowzero_orchestration_service.t_retry_task (biz_id, biz_type);

CREATE INDEX IF NOT EXISTS idx_rt_biz_type_status_next_retry
    ON ratan_flowzero_orchestration_service.t_retry_task (biz_type, status, next_retry_at)
    WHERE status IN ('SUSPENDED', 'FAILED');

CREATE INDEX IF NOT EXISTS idx_rt_payload_gin
    ON ratan_flowzero_orchestration_service.t_retry_task USING GIN (payload);

-- Table and column comments
COMMENT ON TABLE  ratan_flowzero_orchestration_service.t_retry_task                      IS 'Generic third-party retry task table: all external-call failure-retry scenarios (iCDMS sync, email notify, webhook callback, etc.) share this table, differentiated by biz_type';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_retry_task.id                   IS 'Primary key (Snowflake ID, generated by the application layer)';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_retry_task.biz_type             IS 'Business type identifier: ICDMS_SYNC | EMAIL_NOTIFY | WEBHOOK | …';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_retry_task.biz_id               IS 'Business record ID; semantics defined per biz_type (e.g. t_attachments.id for ICDMS_SYNC)';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_retry_task.payload              IS 'Complete parameters (JSONB) required for the external call; used by the retry scheduler directly';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_retry_task.status               IS 'Task status: PENDING | SUCCESS(✅ terminal) | FAILED(data fault, retryable) | SUSPENDED(service fault, waiting) | SKIPPED(⚠️ terminal, alert)';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_retry_task.retry_count          IS 'Number of FAILED (data-fault) retries; SUSPENDED (service-fault) retries do NOT increment this counter; first write: 0 for service fault, 1 for data fault';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_retry_task.max_retry            IS 'Maximum FAILED retries before transitioning to SKIPPED (default 3)';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_retry_task.last_error           IS 'Error message from the most recent failed attempt (truncated to 2000 chars at the application layer)';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_retry_task.next_retry_at        IS 'Earliest retry time (Equal Jitter exponential backoff); NULL = retry immediately (used for recovered SUSPENDED records)';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_retry_task.synced_at            IS 'Timestamp when the external call was acknowledged (SUCCESS state)';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_retry_task.created_at           IS 'Record creation timestamp (auto-populated by JPA auditing)';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_retry_task.updated_at           IS 'Record last-modified timestamp (auto-populated by JPA auditing)';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_retry_task.created_by           IS 'User / system component that created the record';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_retry_task.updated_by           IS 'User / system component that last modified the record';
COMMENT ON COLUMN ratan_flowzero_orchestration_service.t_retry_task.version              IS 'JPA optimistic-lock version counter';
