apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "ratan-nginx-webapp.name" . }}
    app_name: {{ .Release.Name }}
    app_version: {{ .Values.appVersion }}
    chart: {{ template "ratan-nginx-webapp.chart" . }}
    chart_version: {{ .Chart.Version }}
    component: ratan-nginx-webapp
    environment: {{ .Values.environment }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "80"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /index.js
spec:
  selector:
    app: {{ template "ratan-nginx-webapp.name" . }}
    app_name: {{ .Release.Name }}
    app_version: {{ .Values.appVersion }}
    chart: {{ template "ratan-nginx-webapp.chart" . }}
    chart_version: {{ .Chart.Version }}
    component: ratan-nginx-webapp
    environment: {{ .Values.environment }}
  ports:
    - name: http
      port: 80
      targetPort: 8080
  {{- if .Values.service.type }}
  type: {{ .Values.service.type }}
  {{- end }}
