import * as api from './api';
afterAll(() => {
  vi.clearAllMocks();
});

describe("SuppressionRules component", () => {
  it("Should response correct", async () => {
    expect(await api.getWithParams("/")).toEqual({});
    expect(await api.getWithParams("/", { a: 0 })).toEqual({});
    expect(await api.getViewList({ a: 0 })).toEqual({});
    expect(await api.getViewDetails('1', "TRADE_FILTER_BUILDER")).toEqual({});
    expect(await api.postSaveView({ a: 0 })).toEqual({});
    expect(await api.putUpdateView('1', { a: 0 })).toEqual({});
    expect(await api.deleteView('1', "TRADE_FILTER_BUILDER")).toEqual({});
    expect(await api.getFilterList({})).toEqual({});
    expect(await api.getFilterDetails('1', "TRADE_FILTER_BUILDER")).toEqual({});
    expect(await api.postSaveFilter({ a: 0 })).toEqual({});
    expect(await api.putUpdateFilter('1', { a: 0 })).toEqual({});
    expect(await api.deleteFilter('1', "TRADE_FILTER_BUILDER")).toEqual({});
    expect(await api.putReplay('1')).toEqual({});
    expect(await api.postManualFix({ a: 0 })).toEqual({});
    expect(await api.putCloseException('1')).toEqual({});
    expect(await api.postMakerRepair('1', { a: 0 })).toEqual({});
    expect(await api.postCheckerRepair('1', { a: 0 })).toEqual({});
    expect(await api.putCheckerReject('1', { a: 0 })).toEqual({});
    expect(await api.getLookupSSI({ a: 0 })).toEqual({});
    expect(await api.getQueryMultiSSI('1')).toEqual({});
    expect(await api.getQuerySSIDetail('1')).toEqual({});
    expect(await api.postAdhocSSIMaker({ a: 0 })).toEqual({});
    expect(await api.postAdhocSSIChecker({ a: 0 })).toEqual({});
    expect(await api.postAdhocSSIReject({ a: 0 })).toEqual({});
    expect(await api.getAdhocSSI({ cashflowId: '1', cashflowVersion: '0' })).toEqual({});
    expect(await api.getSuppressionRuleList()).toEqual({});
    expect(await api.createSuppressionRule({ a: 0 })).toEqual({});
    expect(await api.changeSuppressionRuleStatus({ a: 0 })).toEqual({});
    expect(await api.approveSuppressionRuleStatus({ a: 0 })).toEqual({});
    expect(await api.getSuppressionRuleHistoryList({ a: 0 })).toEqual({});
    expect(await api.getSettlementRuleList()).toEqual({});
    expect(await api.createSettlementRule({ a: 0 })).toEqual({});
    expect(await api.changeSettlementRuleStatus({ a: 0 })).toEqual({});
    expect(await api.approveSettlementRuleStatus({ a: 0 })).toEqual({});
    expect(await api.getSettlementRuleHistoryList({ a: 0 })).toEqual({});
    expect(await api.getNettingRuleList()).toEqual({});
    expect(await api.createNettingRule({ a: 0 })).toEqual({});
    expect(await api.changeNettingRuleStatus({ a: 0 })).toEqual({});
    expect(await api.approveNettingRuleStatus({ a: 0 })).toEqual({});
    expect(await api.getNettingRuleHistoryList({ a: 0 })).toEqual({});
    expect(await api.getCurrencyRuleList()).toEqual({});
    expect(await api.getCurrencyRuleHistoryList()).toEqual({});
    expect(await api.createCurrencyRule({ a: 0 })).toEqual({});
    expect(await api.changeCurrencyRuleStatus({ a: 0 })).toEqual({});
    expect(await api.getSpecialRuleConfig_NewNSTPRules()).toEqual({});
    expect(await api.addRule_NewRules({ a: 0 })).toEqual({});
    expect(await api.listAllRule_NewRules()).toEqual({});
    expect(await api.listRuleByType_NewRules("a")).toEqual({});
    expect(await api.addSpecialRule_NewNSTPRules({ a: 0 })).toEqual({});
    expect(await api.cancelAddedRule_NewRules({ ruleId: 0 })).toEqual({});
    expect(await api.confirmAddedRule_NewRules({ ruleId: 0 })).toEqual({});
    expect(await api.deleteRule_NewRules({ ruleId: 0 })).toEqual({});
    expect(await api.cancelDeleteRule_NewRules({ ruleId: 0 })).toEqual({});
    expect(await api.confirmDeleteRule_NewRules({ ruleId: 0 })).toEqual({});
    expect(await api.ruleHistories_NewRules({ ruleId: 0 })).toEqual({});
    expect(await api.getEntitlementRuleList()).toEqual({});
    expect(await api.createEntitlementRule({ a: 0 })).toEqual({});
    expect(await api.updateEntitlementRule({ a: 0 })).toEqual({});
    expect(await api.delEntitlementRule({ a: 0 })).toEqual({});
    expect(await api.getMyEntitlementRuleList()).toEqual({});
    expect(await api.getEntitlementRoles()).toEqual({});
    expect(await api.replayTrade({ tradeId: 0 })).toEqual({});
    expect(await api.postTradeAffirmation({ a: 0 })).toEqual({});
    expect(await api.getTradeAffirmation("123")).toEqual({});
    expect(await api.getCurrencyPairsData()).toEqual({});
    expect(await api.postCashAffirmation({ a: 0 })).toEqual({});
    expect(await api.cashflowNetting({ a: 0 })).toEqual({});
    expect(await api.cashflowNettingBAU({ a: 0 })).toEqual({});
    expect(await api.cashflowNettingPreview({ a: 0 })).toEqual({});
    expect(await api.releaseCashflow({ a: 0 })).toEqual({});
    expect(await api.rejectCashflow({ a: 0 })).toEqual({});
    expect(await api.approveCashflow({ a: 0 })).toEqual({});
    expect(await api.cashflowUnNet({ a: 0 })).toEqual({});
    expect(await api.cashflowUnNetBAU({ a: 0 })).toEqual({});
    expect(await api.verifyCashflowUnNet({ a: 0 })).toEqual({});
    expect(await api.rejectCashflowUnNet({ a: 0 })).toEqual({});
    expect(await api.cashflowAddComment({ a: 0 })).toEqual({});
    expect(await api.suppressCashflow({ a: 0 })).toEqual({});
    expect(await api.rejectSuppressCashflow({ a: 0 })).toEqual({});
    expect(await api.approveSuppressCashflow({ a: 0 })).toEqual({});
    expect(await api.requestUnSuppressCashflow({ a: 0 })).toEqual({});
    expect(await api.releaseReceiptCashflow({ a: 0 })).toEqual({});
    expect(await api.rejectReleaseReceiptCashflow({ a: 0 })).toEqual({});
    expect(await api.approveReleaseReceiptCashflow({ a: 0 })).toEqual({});
    expect(await api.releasePaymentCashflow({ a: 0 })).toEqual({});
    expect(await api.rejectReleasePaymentCashflow({ a: 0 })).toEqual({});
    expect(await api.approveReleasePaymentCashflow({ a: 0 })).toEqual({});
    expect(await api.getCashflowSubStatusList()).toEqual({});
    expect(await api.swiftMessageDetails({ a: 0 })).toEqual({});
    expect(await api.getNostroDetail({ a: 0 })).toEqual({});
    expect(await api.getNostroList({ legalEntity: 'xx', currency: 'RUB' })).toEqual({});
    expect(await api.postMakerNostro({ a: 0 })).toEqual({});
    expect(await api.postCheckerNostro({ a: 0 })).toEqual({});
    expect(await api.postRejectNostro({ a: 0 })).toEqual({});
    expect(await api.getVostroDetail({ a: 0 })).toEqual({});
    expect(await api.getValidationRules('SSI')).toEqual({});
    expect(await api.getPreference()).toEqual({});
    expect(await api.putPreference({ a: 0 })).toEqual({});
    expect(await api.getBusinessFieldsVersion()).toEqual({});
    expect(await api.getBusinessFieldsTrade('trade')).toEqual({});
    expect(await api.getBusinessFieldsCashflow('trade')).toEqual({});
    expect(await api.fetchVostroForOscarStamping({ a: 0 })).toEqual({});
    expect(await api.getNostroForOscar({ a: 0, b: 0 })).toEqual({});
    expect(await api.getCurrencyList()).toEqual({});
    expect(await api.checkerApproveCurrency({ a: 0 })).toEqual({});
    expect(await api.deleteCurrency({ a: 0 })).toEqual({});
    expect(await api.checkerRejectCurrency({ a: 0 })).toEqual({});
    expect(await api.postReinstate({ a: 0 })).toEqual({});
    expect(await api.cashflowHold({ a: 0 })).toEqual({});
    expect(await api.cashflowUnhold({ a: 0 })).toEqual({});
    expect(await api.createCurrency ({ a: 0 })).toEqual({});
    expect(await api.queryHolidy  ({ a: 0 })).toEqual({});
  });
  it("Should response correct when disable feature", async () => {
    expect(await api.getWithParams("/")).toEqual({});
    expect(await api.getWithParams("/", { a: 0 })).toEqual({});
    expect(await api.getViewList({ a: 0 })).toEqual({});
    expect(await api.getViewDetails('1', "TRADE_FILTER_BUILDER")).toEqual({});
    expect(await api.postSaveView({ a: 0 })).toEqual({});
    expect(await api.putUpdateView('1', { a: 0 })).toEqual({});
    expect(await api.deleteView('1', "TRADE_FILTER_BUILDER")).toEqual({});
    expect(await api.getFilterList({})).toEqual({});
    expect(await api.getFilterDetails('1', "TRADE_FILTER_BUILDER")).toEqual({});
    expect(await api.postSaveFilter({ a: 0 })).toEqual({});
    expect(await api.putUpdateFilter('1', { a: 0 })).toEqual({});
    expect(await api.deleteFilter('1', "TRADE_FILTER_BUILDER")).toEqual({});
    expect(await api.putReplay('1')).toEqual({});
    expect(await api.postManualFix({ a: 0 })).toEqual({});
    expect(await api.putCloseException('1')).toEqual({});
    expect(await api.postMakerRepair('1', { a: 0 })).toEqual({});
    expect(await api.postCheckerRepair('1', { a: 0 })).toEqual({});
    expect(await api.putCheckerReject('1', { a: 0 })).toEqual({});
    expect(await api.getLookupSSI({ a: 0 })).toEqual({});
    expect(await api.getQueryMultiSSI('1')).toEqual({});
    expect(await api.getQuerySSIDetail('1')).toEqual({});
    expect(await api.postAdhocSSIMaker({ a: 0 })).toEqual({});
    expect(await api.postAdhocSSIChecker({ a: 0 })).toEqual({});
    expect(await api.postAdhocSSIReject({ a: 0 })).toEqual({});
    expect(await api.getAdhocSSI({ cashflowId: '1', cashflowVersion: '0' })).toEqual({});
    expect(await api.getSuppressionRuleList()).toEqual({});
    expect(await api.createSuppressionRule({ a: 0 })).toEqual({});
    expect(await api.changeSuppressionRuleStatus({ a: 0 })).toEqual({});
    expect(await api.approveSuppressionRuleStatus({ a: 0 })).toEqual({});
    expect(await api.getSuppressionRuleHistoryList({ a: 0 })).toEqual({});
    expect(await api.getSettlementRuleList()).toEqual({});
    expect(await api.createSettlementRule({ a: 0 })).toEqual({});
    expect(await api.changeSettlementRuleStatus({ a: 0 })).toEqual({});
    expect(await api.approveSettlementRuleStatus({ a: 0 })).toEqual({});
    expect(await api.getSettlementRuleHistoryList({ a: 0 })).toEqual({});
    expect(await api.getNettingRuleList()).toEqual({});
    expect(await api.createNettingRule({ a: 0 })).toEqual({});
    expect(await api.changeNettingRuleStatus({ a: 0 })).toEqual({});
    expect(await api.approveNettingRuleStatus({ a: 0 })).toEqual({});
    expect(await api.getNettingRuleHistoryList({ a: 0 })).toEqual({});
    expect(await api.getCurrencyRuleList()).toEqual({});
    expect(await api.getCurrencyRuleHistoryList()).toEqual({});
    expect(await api.createCurrencyRule({ a: 0 })).toEqual({});
    expect(await api.changeCurrencyRuleStatus({ a: 0 })).toEqual({});
    expect(await api.getSpecialRuleConfig_NewNSTPRules()).toEqual({});
    expect(await api.addRule_NewRules({ a: 0 })).toEqual({});
    expect(await api.listAllRule_NewRules()).toEqual({});
    expect(await api.listRuleByType_NewRules("a")).toEqual({});
    expect(await api.addSpecialRule_NewNSTPRules({ a: 0 })).toEqual({});
    expect(await api.cancelAddedRule_NewRules({ ruleId: 0 })).toEqual({});
    expect(await api.confirmAddedRule_NewRules({ ruleId: 0 })).toEqual({});
    expect(await api.deleteRule_NewRules({ ruleId: 0 })).toEqual({});
    expect(await api.cancelDeleteRule_NewRules({ ruleId: 0 })).toEqual({});
    expect(await api.confirmDeleteRule_NewRules({ ruleId: 0 })).toEqual({});
    expect(await api.ruleHistories_NewRules({ ruleId: 0 })).toEqual({});
    expect(await api.getEntitlementRuleList()).toEqual({});
    expect(await api.createEntitlementRule({ a: 0 })).toEqual({});
    expect(await api.updateEntitlementRule({ a: 0 })).toEqual({});
    expect(await api.delEntitlementRule({ a: 0 })).toEqual({});
    expect(await api.getMyEntitlementRuleList()).toEqual({});
    expect(await api.getEntitlementRoles()).toEqual({});
    expect(await api.replayTrade({ tradeId: 0 })).toEqual({});
    expect(await api.postTradeAffirmation({ a: 0 })).toEqual({});
    expect(await api.getTradeAffirmation("123")).toEqual({});
    expect(await api.getCurrencyPairsData()).toEqual({});
    expect(await api.postCashAffirmation({ a: 0 })).toEqual({});
    expect(await api.cashflowNetting({ a: 0 })).toEqual({});
    expect(await api.cashflowNettingBAU({ a: 0 })).toEqual({});
    expect(await api.cashflowNettingPreview({ a: 0 })).toEqual({});
    expect(await api.releaseCashflow({ a: 0 })).toEqual({});
    expect(await api.rejectCashflow({ a: 0 })).toEqual({});
    expect(await api.approveCashflow({ a: 0 })).toEqual({});
    expect(await api.cashflowUnNet({ a: 0 })).toEqual({});
    expect(await api.cashflowUnNetBAU({ a: 0 })).toEqual({});
    expect(await api.verifyCashflowUnNet({ a: 0 })).toEqual({});
    expect(await api.rejectCashflowUnNet({ a: 0 })).toEqual({});
    expect(await api.cashflowAddComment({ a: 0 })).toEqual({});
    expect(await api.suppressCashflow({ a: 0 })).toEqual({});
    expect(await api.rejectSuppressCashflow({ a: 0 })).toEqual({});
    expect(await api.approveSuppressCashflow({ a: 0 })).toEqual({});
    expect(await api.requestUnSuppressCashflow({ a: 0 })).toEqual({});
    expect(await api.releaseReceiptCashflow({ a: 0 })).toEqual({});
    expect(await api.rejectReleaseReceiptCashflow({ a: 0 })).toEqual({});
    expect(await api.approveReleaseReceiptCashflow({ a: 0 })).toEqual({});
    expect(await api.releasePaymentCashflow({ a: 0 })).toEqual({});
    expect(await api.rejectReleasePaymentCashflow({ a: 0 })).toEqual({});
    expect(await api.approveReleasePaymentCashflow({ a: 0 })).toEqual({});
    expect(await api.getCashflowSubStatusList()).toEqual({});
    expect(await api.swiftMessageDetails({ a: 0 })).toEqual({});
    expect(await api.getNostroDetail({ a: 0 })).toEqual({});
    expect(await api.getNostroList({ legalEntity: 'xx', currency: 'RUB' })).toEqual({});
    expect(await api.postMakerNostro({ a: 0 })).toEqual({});
    expect(await api.postCheckerNostro({ a: 0 })).toEqual({});
    expect(await api.postRejectNostro({ a: 0 })).toEqual({});
    expect(await api.getVostroDetail({ a: 0 })).toEqual({});
    expect(await api.getValidationRules('SSI')).toEqual({});
    expect(await api.getPreference()).toEqual({});
    expect(await api.putPreference({ a: 0 })).toEqual({});
    expect(await api.getBusinessFieldsVersion()).toEqual({});
    expect(await api.getBusinessFieldsTrade('trade')).toEqual({});
    expect(await api.getBusinessFieldsCashflow('trade')).toEqual({});
    expect(await api.fetchVostroForOscarStamping({ a: 0 })).toEqual({});
    expect(await api.getNostroForOscar({ a: 0, b: 0 })).toEqual({});
    expect(await api.getCurrencyList()).toEqual({});
    expect(await api.checkerApproveCurrency({ a: 0 })).toEqual({});
    expect(await api.deleteCurrency({ a: 0 })).toEqual({});
    expect(await api.checkerRejectCurrency({ a: 0 })).toEqual({});
    expect(await api.postReinstate({ a: 0 })).toEqual({});
    expect(await api.cashflowHold({ a: 0 })).toEqual({});
    expect(await api.cashflowUnhold({ a: 0 })).toEqual({});
    expect(await api.createCurrency ({ a: 0 })).toEqual({});
    expect(await api.queryHolidy  ({ a: 0 })).toEqual({});
  });
});

