# config all KEYS to be in CAPS
PORT_NO = 8080
URL_PREFIX = "/api/exp/v1"

# Graphql Security Extensions
GRAPHQL_MAX_DEPTH = 10
GRAPHQL_MAX_ALIAS_COUNT = 10
GRAPHQL_MAX_TOKEN_COUNT = 1000
GRAPHQL_ENABLE_INTERFACE = False
GRAPHQL_DISABLE_INTROSPECTION = True