quarkus.http.port=8080
quarkus.http.host=0.0.0.0
quarkus.grpc.dev-mode.force-server-start=false
quarkus.otel.enabled=false
devkit.federated.supported.packages=com.sc.faas.dto
quarkus.native.additional-build-args=-H:+UnlockExperimentalVMOptions,-H:ReflectionConfigurationFiles=reflect-config.json,-H:ResourceConfigurationFiles=resource-config.json,-H:DeadlockWatchdogInterval=60000,-H:-UnlockExperimentalVMOptions,-H:+ReportExceptionStackTraces,--verbose,--initialize-at-run-time=graphql.util.IdGenerator,--initialize-at-build-time=kotlin\\,ch.qos.logback\\,org.slf4j,--parallelism=4,-march=compatibility
quarkus.native.resources.includes=i18n/**,.*\\.graphqls$,.*\\.sdl$,.*\\.json$