<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.sc.devkit</groupId>
        <artifactId>process-parent-java</artifactId>
        <version>1.0.0-2640245</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <groupId>com.sc.api</groupId>
    <artifactId>artifact</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <!-- Additional properties for dependencies required to compile the project, remove after -->
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.sc.devkit.api</groupId>
            <artifactId>devkit-api-common</artifactId>
            <version>2.0.0-5028335</version>
        </dependency>
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>1.5.22</version>
        </dependency>
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-jaxrs</artifactId>
            <version>1.5.22</version>
        </dependency>
        <dependency>
            <groupId>joda-time</groupId>
            <artifactId>joda-time</artifactId>
            <version>2.10.13</version>
        </dependency>
        <dependency>
            <groupId>com.sun.jersey</groupId>
            <artifactId>jersey-bundle</artifactId>
            <version>1.19.4</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>7.11.0</version>
                <executions>
                    <execution>
                        <id>generate-example</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <generatorName>jaxrs-spec</generatorName>
                            <generateModels>true</generateModels>
                            <skipValidateSpec>true</skipValidateSpec>
                            <ignoreFileOverride>.openapi-generator-ignore</ignoreFileOverride>
                            <configOptions>
                                <withXml>false</withXml>
                                <generateConstructorWithAllArgs>false</generateConstructorWithAllArgs>
                                <sourceFolder>src/main/java</sourceFolder>
                                <generateBuilders>false</generateBuilders>
                                <useJakartaEe>true</useJakartaEe>
                                <useBeanValidation>true</useBeanValidation>
                                <apiPackage>com.sc.api.generated.api</apiPackage>
                                <modelPackage>com.sc.api.generated.model</modelPackage>
                                <interfaceOnly>true</interfaceOnly>
                                <returnResponse>false</returnResponse>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                                <library>quarkus</library>
                            </configOptions>
                            <inputSpec>src/main/resources/openapi.json</inputSpec>
                            <templateDirectory>src/main/resources/templates</templateDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.spotify.fmt</groupId>
                <artifactId>fmt-maven-plugin</artifactId>
                <version>2.25</version> <!-- Check for latest version -->
                <executions>
                    <execution>
                        <goals>
                            <goal>format</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <style>aosp</style>
                    <additionalSourceDirectories>
                        <param>target</param>
                    </additionalSourceDirectories>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <excludes>
                        <exclude>target</exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>