export declare const Icons: {
    'country-ago': string;
    'country-are': string;
    'country-arg': string;
    'country-aus': string;
    'country-bgd': string;
    'country-bhr': string;
    'country-bra': string;
    'country-brn': string;
    'country-bwa': string;
    'country-chn': string;
    'country-civ': string;
    'country-cmr': string;
    'country-col': string;
    'country-deu': string;
    'country-egy': string;
    'country-flk': string;
    'country-fra': string;
    'country-gbr': string;
    'country-ggy': string;
    'country-gha': string;
    'country-gmb': string;
    'country-hkg': string;
    'country-idn': string;
    'country-ind': string;
    'country-irl': string;
    'country-irq': string;
    'country-jor': string;
    'country-jpn': string;
    'country-ken': string;
    'country-khm': string;
    'country-kor': string;
    'country-lao': string;
    'country-lbn': string;
    'country-lka': string;
    'country-mac': string;
    'country-mmr': string;
    'country-mus': string;
    'country-mys': string;
    'country-nga': string;
    'country-npl': string;
    'country-off': string;
    'country-omn': string;
    'country-pak': string;
    'country-phl': string;
    'country-pol': string;
    'country-qat': string;
    'country-sau': string;
    'country-sgp': string;
    'country-sle': string;
    'country-swe': string;
    'country-tha': string;
    'country-tur': string;
    'country-twn': string;
    'country-tza': string;
    'country-uga': string;
    'country-usa': string;
    'country-vnm': string;
    'country-zaf': string;
    'country-zmb': string;
    'country-zwe': string;
};
export declare const CountryIconLibrary: {
    name: string;
    resolver: (name: keyof typeof Icons) => string;
};
export default CountryIconLibrary;
