uklvadapp759 ansible_host=10.198.197.49 ansible_connection=ssh ansible_port=22 ansible_user=tsp-release
uklvadapp760 ansible_host=10.198.197.50 ansible_connection=ssh ansible_port=22 ansible_user=tsp-release

[uat_app_server]
uklvadapp759
uklvadapp760

[all_server]
uklvadapp759
uklvadapp760

[web_server]
uklvadapp759
uklvadapp760

[uat_app_server:vars]
env=uat
maven_package_repo_dir=maven-sc-release_local
npm_package_repo_dir=npm-release
generic_package_repo_dir=generic-release
docker_repo=artifactory.global.standardchartered.com
cdn_url_prefix=https://uat-cdn.leap.standardchartered.com
eurekaDefaultZone=https://uklvadapp759.uk.dev.net:8761/eureka,https://uklvadapp760.uk.dev.net:8761/eureka

[all_server:vars]
artifact_repo=https://artifactory.global.standardchartered.com/artifactory
temp_deploy_dir=/tmp/tsp
apps_logs_dir=/apps/tsp/logs/
region=uk
python_path=/apps/tsp/python-env/bin/python
pip_path=/apps/tsp/python-env/bin/pip
db_password_file=/apps/tsp/security/aLicence.txt
ld_library_path=/usr/lib/oracle/12.1/client64/lib/
service_script=/usr/sbin/service
app_deploy_dir=/apps/tsp
web_deploy_dir=/apps/tsp/html
httpd_dir=/etc/httpd
apache2_dir=/usr/local/apache2
apache24_dir=/usr/local/apache24
