import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  resolve: {
    dedupe: [
      "react",
      "react-dom",
      "@mui/material",
      "@mui/system",
      "@emotion/react",
      "@emotion/styled",
    ],
  },
  build: {
    lib: {
      entry: {
        index: "src/index.ts",
        Button: "src/Button.tsx",
        LoadingButton: "src/LoadingButton.tsx",
        Input: "src/Input.tsx",
        Select: "src/Select.tsx",
        SearchInput: "src/SearchInput.tsx",
        SearchButton: "src/SearchButton.tsx",
        ResetButton: "src/ResetButton.tsx",
        SearchGrid: "src/SearchGrid.tsx",
        SearchCondition: "src/SearchCondition.tsx",
        SearchConditionContainer: "src/SearchConditionContainer.tsx",
        ToggleButton: "src/ToggleButton.tsx",
        Label: "src/Label.tsx",
        LabelMenuItem: "src/LabelMenuItem.tsx",
        Loader: "src/Loader.tsx",
        PageLoader: "src/PageLoader.tsx",
        Snackbar: "src/Snackbar.tsx",
        Dialog: "src/Dialog.tsx",
        EmptyState: "src/EmptyState.tsx",
        ErrorFallback: "src/ErrorFallback.tsx",
        LoadingOverlay: "src/LoadingOverlay.tsx",
        Spinner: "src/Spinner.ts",
        BuilderButton: "src/BuilderButton.tsx",
        BuilderTabs: "src/BuilderTabs.tsx",
        BuilderTab: "src/BuilderTab.tsx",
        BuilderTabPanel: "src/BuilderTabPanel.tsx",
        DatePicker: "src/DatePicker.tsx",
        DateTimePicker: "src/DateTimePicker.tsx",
        TimePicker: "src/TimePicker.tsx",
        Provider: "src/Provider.tsx",
        appearance: "src/appearance.ts",
        theme: "src/theme/index.ts",
        tokens: "src/tokens/index.ts",
        compatibility: "src/compatibility.ts",
        "base-compat": "src/base-compat.tsx",
        dates: "src/dates.tsx",
        "date-range": "src/date-range.tsx",
        "portal-theme": "src/portal-theme.ts",
      },
      formats: ["es"],
      fileName: (_format, name) => `${name}.js`,
    },
    rolldownOptions: {
      external:
        /^(react|react-dom|@mui\/material|@mui\/icons-material|@mui\/x-date-pickers|@mui\/x-date-pickers-pro|dayjs|@emotion\/react|@emotion\/styled)(\/|$)/,
      output: {
        preserveModules: true,
        preserveModulesRoot: "src",
      },
    },
  },
});
