quarkus.otel.enabled=false
quarkus.funqy.export=handler

# Injection for devkit common lib
quarkus.index-dependency.devkit.group-id=com.sc.devkit.api
quarkus.index-dependency.devkit.artifact-id=devkit-api-common
quarkus.tls.trust-all=true

quarkus.funqy.knative-events.mapping.handler.trigger=${DOMAIN_JOB_ITAM}-${DOMAIN_JOB_NAME}
quarkus.funqy.knative-events.mapping.handler.response-source=/apis/v1/namespaces/55313/pingsources/${PING_SOURCE_NAME}
quarkus.funqy.knative-events.mapping.handler.response-type=${DOMAIN_JOB_ITAM}-${DOMAIN_JOB_NAME}
