import { html, TemplateResult } from 'lit';
// eslint-disable-next-line import/extensions
import '@scdevkit/form/elements';

const Definition = {
  id: '16846fab-d24b-4842-8a4f-dc3426903b05',
  layout: {
    row: '75813e44-6aac-4c0c-ad44-3337876c00d2',
  },
  pages: [
    {
      id: '9e21c492-fcd1-437e-a13b-a0e0bb3d5163',
      layout: {
        row: 'ca1f3d98-6c4f-4b44-8835-6ed50b924dc6',
      },
      components: [
        {
          id: 'f99a1803-d905-4043-9051-a1716b348473',
          layout: {
            row: 'f6492365-330d-48c7-94a1-817ae9e51969',
          },
          type: 'text-field',
          template: {
            label: 'Name',
          },
        },
        {
          id: 'ae67ad77-3483-4dca-a848-3a0382f0b8c9',
          layout: {
            row: 'f6492365-330d-48c7-94a1-817ae9e51969',
          },
          type: 'number-input',
          template: {
            label: 'Age',
          },
        },
        {
          id: '1dbd41ac-6403-48d8-a2e0-d4d640d2837d',
          layout: {
            row: 'f6492365-330d-48c7-94a1-817ae9e51969',
          },
          type: 'text-field',
          template: {
            label: 'Sex',
          },
        },
        {
          id: '44aed6f7-1733-4b37-9a6a-d0bd448f42a2',
          layout: {
            row: '120d5b57-f040-4654-91ff-c05867339bf7',
          },
          type: 'box',
          template: {
            label: 'Basic information',
          },
          components: [
            {
              id: '3347c03d-37e0-4915-bc9a-bbda49078390',
              layout: {
                row: 'fb10e2bd-5153-4273-b5a7-bea842eca36f',
              },
              type: 'dropdown-input',
              template: {
                label: 'Country',
                options: [
                  {
                    value: 'CN',
                    label: 'China',
                  },
                  {
                    value: 'SG',
                    label: 'Singapore',
                  },
                ],
              },
            },
            {
              id: 'f2bdd986-f167-4659-89fe-28b8f292d5ae',
              layout: {
                row: 'fb10e2bd-5153-4273-b5a7-bea842eca36f',
              },
              type: 'text-field',
              template: {
                label: 'Phone',
              },
            },
          ],
        },
      ],
    },
  ],
  version: '1',
};

const Data = [
  {
    id: 'f99a1803-d905-4043-9051-a1716b348473',
    value: 'Rose',
    type: 'text-field',
    label: 'Name',
  },
  {
    id: 'ae67ad77-3483-4dca-a848-3a0382f0b8c9',
    value: '32',
    type: 'number-input',
    label: 'Age',
  },
  {
    id: '1dbd41ac-6403-48d8-a2e0-d4d640d2837d',
    value: 'female',
    type: 'text-field',
    label: 'Sex',
  },
  {
    id: '3347c03d-37e0-4915-bc9a-bbda49078390',
    value: 'CN',
    type: 'dropdown-input',
    label: 'Country',
  },
  {
    id: 'f2bdd986-f167-4659-89fe-28b8f292d5ae',
    value: '123456',
    type: 'text-field',
    label: 'Phone',
  },
];
export default {
  title: 'Form/Form Viewer',
  component: 'sc-form-viewer',
  parameters: {
    docs: {
      description: {
        component:
          `Form viewer is used to render a form created by form editor. To learn more, please go
          <sc-link href='/form-designer/editor' target='_blank'>Form Designer</sc-link>`,
      },
    },
  },
  tags: ['autodocs'],
  argTypes: {
    definition: {
      control: 'object',
      description: 'Form definition which generated by form editor, it defines the form\'s components and layout',
      table: {
        type: { summary: 'object' },
        category: 'Attributes',
      },
    },   
    data: {
      control: 'array',
      description: 'Form components\' value.',
      table: {
        type: { summary: 'array' },
        defaultValue: { summary: false },
        category: 'Attributes',
      },
    },
    readonly: {
      control: 'boolean',
      description: 'Sets to disable editing of the form.',
      table: {
        type: { summary: 'boolean' },
        defaultValue: { summary: false },
        category: 'Attributes',
      },
    }, 
    'value-changed': {
      description: `Emitted when the form component\'s value changes, 
      can use it to get the latest data from the event.detail.data.`,
      table: {
        type: { summary: 'CustomEvent' },
        category: 'Custom Events',
      },
    },
  },
  args: {
    definition: Definition,
    data: Data,
    readonly: false,
  },
};

interface Story<T> {
  (args: T): TemplateResult;
  args?: Partial<T>;
  argTypes?: Record<string, unknown>;
}

interface ArgTypes {
  definition: object;
  data: object;
  readonly: boolean;
}

const Template: Story<ArgTypes> = (props: ArgTypes) =>
  props.readonly ? html`
    <sc-form-viewer readonly .definition=${props.definition} .data=${props.data}></sc-form-viewer>
  ` : html`
    <sc-form-viewer .definition=${props.definition} .data=${props.data}></sc-form-viewer>  
  `;

export const WithData = Template.bind({});
WithData.args = {
  data: Data,
};

export const Readonly = Template.bind({});
Readonly.args = {
  readonly: true,
  data: Data,
};
