/// <reference types="single-spa" />
export declare const bootstrap: import("single-spa").LifeCycleFn<{}>,
  unmount: import("single-spa").LifeCycleFn<{}>;
export declare const render: (rootComp: any, props: any) => void;
export declare const check: (rootComp: any, props: any) => void;
export declare function MountComponent(props: any): Promise<void>;
export declare const mount: import("single-spa").LifeCycleFn<{}>;
export * as Analytics from "./analytics";
export * as BuilderButton from "./components/BuilderButton";
export * as Button from "./components/Button";
export * as DatePicker from "./components/DatePicker";
export * as DateRangePicker from "./components/DateRangePicker";
export * as DateTimePicker from "./components/DateTimePicker";
export * as Dialog from "./components/Dialog";
export * as Drawer from "./components/Drawer";
export * as ErrorBoundry from "./components/ErrorBoundry";
export * as Input from "./components/Input";
export * as Label from "./components/Label";
export * as Loader from "./components/Loader";
export * as LoaderProps from "./components/Loader/common/type";
export * as PageLoader from "./components/Loader/PageLoader";
export * as LoadingButton from "./components/LoadingButton";
export * as LoadingButtonProps from "./components/LoadingButton/interface";
export * as ResetButton from "./components/ResetButton";
export * as ScWebkit from "./components/ScWebkit";
export * as SearchButton from "./components/SearchButton";
export * as SearchCondition from "./components/SearchCondition";
export * as SearchConditionContainer from "./components/SearchConditionContainer";
export * as SearchGrid from "./components/SearchGrid";
export * as SearchInput from "./components/SearchInput";
export * as Select from "./components/Select";
export * as Snackbar from "./components/Snackbar";
export * as Splash from "./components/Splash";
export * as Time from "./components/Time";
export * as TimePicker from "./components/TimePicker";
export * as ToggleButton from "./components/ToggleButton";
export * as Version from "./components/Version";
export * as Hooks from "./hooks";
export * as Dispatcher from "./hooks/dispathcer";
export * as Provider from "./hooks/provider";
export * as Reduces from "./hooks/reducer";
export * as ActionType from "./hooks/reducer/util/ActionType";
export * as Service from "./hooks/service";
export * as ExtendService from "./hooks/service/util/extend";
export * as Services from "./services";
export * as ThemeConfig from "./theme/Config";
export * as ThemeUtil from "./theme/config/utils";
export * as ThemeProvider from "./theme/Provider";
export * as CommonUtil from "./utils/common";
export * as ChannelUtil from "./utils/drawer";
export * as LocaleUtil from "./utils/locale";
export * as LoginUtil from "./utils/login";
export * as ReactWrapper from "./utils/ReactWrapper";
export * as ReactRouterDom from "react-router-dom";
