apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - edge/configmap.yaml
  - ratan-edge/configmap.yaml
  - workloads.yaml
  - portal-services.yaml
  - services.yaml
  - ingress.yaml
  - pdb.yaml
  - network-policies.yaml
