trigger:
- develop
- release/*
- main
 
parameters:
 - name: releaseId
   type: string
   displayName: Release WorkItem ID
 
resources:
  repositories:
    - repository: governed-templates
      name: dj-core/governed-templates
      ref: "main"
      type: git
 
variables:
  - name: BRANCH_NAME
    value: $(Build.SourceBranchName)
  - name: VERSION
    value: '1.0.0-SNAPSHOT-$(Build.BuildId)'
 
 
extends:
  template: governed-template/build.yml@governed-templates
  parameters:
      releaseId: ${{ parameters.releaseId }}
      buildStackName: node
      buildStackParams:
        pool: 'sc-linux'
        nodeVersion: '16.10.0' #optional
        npmTaskList:
            - name: 'Run Test'
              task: run test
            - name: 'Run Build'
              task: run build
            - name: 'Run Bundle'
              task: run bundle         
        useYarn: false   #optional
        packageVersion: 1.0.0 #optionl
        generateCodeCoverage: 'true'#optional      
        testResultsFiles: '**/TEST-*.xml' #optional
        coverageSummaryFileLocation: 'coverage/cobertura-coverage.xml' #optional
        sonarCoveragePath: 'coverage/lcov.info' #optional
        npmFilePath: foldername (src/app) #optional   dockerBuild: true #optional
        # If you want set specific path for Jfrog Artifacoty as project build file like TGZ except Multiple Project
        npmRepoName: 'npm-release/com/scb'(Default path is "npm-sc-release_local_new" )
        # If your project is UI like ReactJS ,Angular etc.., If you want to use NPM then need to add below details
        uiNpmApp: true
        uiNpmBuildDir: build or dist
        # If your project is UI like ReactJS ,Angular etc.., If you want to use YARNthen to add below details
        uiYarnApp: true
        uiYarnBuildDir: build or dist      
        # If you want to use yarn ,need to add below details
        yarnFilePath: foldername (src/app) #optional
        yarnTaskList:         
            - name: "Run Test"
              task: run ci:tests
            - name: "Run Build"
              task: run build
            - name: "Run Pack"
              task: publish  
        dockerBuild: true #optional
        dockerRepository: '/tde/ado' #optional
        dockerFilePaths:   
          - path: '$(Build.Repository.Name)/dtp-credence-client-request-handler-service/Dockerfile'
            imageName: 'dtp-credence-client-request-handler-service'
            imageTag: '$(BRANCH_NAME)-$(Build.BuildId)'
            dockerArguments: '--build-arg version=$(VERSION)'
            dockerBuildContext: '$(Build.Repository.Name)'
          - path: '$(Build.Repository.Name)/dtp-credence-client-controller/Dockerfile'
            imageName: 'dtp-credence-client-controller'
            imageTag: '$(BRANCH_NAME)-$(Build.BuildId)'
            dockerArguments: '--build-arg version=$(VERSION)'
            dockerBuildContext: '$(Build.Repository.Name)'
        deployStackName: 'ansible' #optional
        deploymentFolderName: 'ado-playbooks' #optional
        sonarExclusions: './src/test/**/*.java'
        imageListFilePath: images.yml #optional   
        skipEarlyFeedback: true #optional [To skip Early Feedback stage]
        useNpmCI : true  # if want to run NPM clean install dependencies command       
        testCoveragePath: 'fssservices-userProvision\coverage\lcov.info'
        #If want to pass unit test case report path. [Default path is coverage/lcov-report]
        calculateImageDigest: true
        preInputFileList: ["helm/Chart.yaml"]
        prevariableList:
          - name : imageTag
            value: $(Build.BuildId)
          - name : chartVersionTag
            value: $(Build.BuildId)
        postinputFileList: ["helm/values.yaml"]
        postvariableList:
          - name : IMAGE_DIGEST
            value: $(DockerImageDigest_nodeapp)
 
    # Add below details ,If you want to run multiple project .      
            multipleModule: true    
        # mention the name and path for where Package.json in project. U can give Path is empty if only one package.json whixh kept in root folder.
            multipleInstallPackageList:
             - name: "51213-leap-kit"
               path:
        # mention the name and path for where Package.json. Need to mention path for specific path for npm package json(Inside folder).            
            MultipleInstallPackageList:
              - name: "scale-web"
                path:  scale-web
  
              - name: "scale-retail-web"
                path:  scale-retail-web
  
        # if want to run npm command on each package
            MultipleTaskList:
  
              - name: 'Run Clean'
                task: run deployall:clean
                path: scale-web
  
              - name: 'run build'
                task: run deployparallel
                path: scale-web
  
              - name: 'Run Clean'
                task: run deployall:clean
                path: scale-retail-web
  
              - name: 'run build'
                task: run deployall --loglevel verbose
                path: scale-retail-web
  
        # if want to package on each package 
            multiplePackageList:
  
              - name: "create-tool"
                path:  packages/create-tool/
  
              - name: "sdk"
                path:  packages/sdk/
  
              - name: "ui-components"
                path:  packages/ui-components/