import type { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  overwrite: true,
  schema: ["graphql-schema/*.graphqls"],
  documents: ["src/**/*.graphqls"],
  debug: true,
  verbose: true,
  generates: {
    "src/generated/types.generated.ts": {
      plugins: ["typescript"],
      config: {
        // maybeValue: "T"
      },
    },
    "src/": {
      preset: "near-operation-file",
      presetConfig: {
        baseTypesPath: "generated/types.generated.ts",
      },
      config: {
        // maybeValue: "T",
      },
      plugins: [
        // {
        //   add: [
        //     {
        //       content: `/* eslint-disable */
        //             /**
        //              *
        //              * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
        //              *
        //              * instead, edit one of the \`.graphqls\` files in this project and run
        //             *
        //             * npm run graphql-codegen
        //             *
        //             * for this file to be re-created
        //             */`,
        //     },
        //     {
        //       content: "module.hot?.accept();",
        //     },
        //   ],
        // },
        "typescript-operations",
        {
          "typescript-rtk-query": {
            importBaseApiFrom: "src/Root/rtk-query/baseGraphQLApi",
            exportHooks: true,
            overrideExisting: 'module.hot?.status() === "apply"',
          },
        },
      ],
    },
  },
};

export default config;
