import type { RootModel } from '../../model/root';

export interface IAction {
  type: ActionType;
  data: RootModel;
}

export enum ActionType {
  SET_TOKEN = 'SET_TOKEN',
  SET_REFRESH_TOKEN = 'SET_REFRESH_TOKEN',
  SET_EXPIRED_TOKEN = 'SET_EXPIRED_TOKEN',
  SET_ERRORMSG = 'SET_ERRORMSG',
  CLEAR = 'CLEAR',
  SET_USER = 'SET_USER',
  SET_IS_LOADING = 'SET_IS_LOADING',
  SET_THEME = 'SET_THEME',
  SET_IS_OPENFIN = 'SET_IS_OPENFIN',
  SET_CLIENT_BUS = 'SET_CLIENT_BUS',
  SET_DRAWER = 'SET_DRAWER',
  SET_WORKSPACES = 'SET_WORKSPACES',
  ADD_WORKSPACE = 'ADD_WORKSPACE',
  SET_CURRENT_WORKSPACES = 'SET_CURRENT_WORKSPACES',
  SET_TIME_TYPE = 'SET_TIME_TYPE',
  SET_ENTITIES = 'SET_ENTITIES',
  SET_REFRESH_TAB = 'SET_REFRESH_TAB',
  SET_ENTITLEMENTS_TOKEN = 'SET_ENTITLEMENTS_TOKEN',
  SET_IS_ON_LOGOUT = 'SET_IS_ON_LOGOUT',
  SET_DRAWERS = 'SET_DRAWERS',
}
