/** Base-owned branding and geometry measured from the Portal reference frames. */
export const portalTokens = {
  fontFamily: '"SC Prosper Sans", Arial, sans-serif',
  color: {
    primary: '#0473ea',
    primaryHover: '#025dbd',
    primaryText: '#ffffff',
    headerText: '#e5f1fc',
    headerMuted: '#b3d5f8',
    headerControl: 'rgba(179, 213, 248, 0.28)',
    headerControlHover: 'rgba(179, 213, 248, 0.44)',
    headerBackgroundLight: '#020b43',
    headerBackgroundDark: '#012e5d',
    headerBackgroundDarkGlow: '#013771',
    headerIconFilter:
      'brightness(0) saturate(100%) invert(88%) sepia(13%) saturate(543%) hue-rotate(178deg) brightness(103%) contrast(98%)',
    backdrop: 'rgba(0, 0, 0, 0.54)',
    light: {
      canvas: '#ffffff',
      text: '#1a1a1a',
      muted: '#666666',
      divider: '#cccccc',
      stripe: '#f8f8f8',
      selected: '#e5f1fc',
      selectedText: '#0250a3',
      chip: '#e5e5e5',
    },
    dark: {
      canvas: '#1a1a1a',
      text: '#eeeeee',
      muted: '#b0b0b0',
      divider: '#666666',
      stripe: '#303030',
      selected: '#001c33',
      selectedText: '#e5f1fc',
      chip: '#151515',
    },
  },
  size: {
    headerHeight: 94,
    headerToolbarHeight: 46,
    headerMobileHeight: 140,
    headerIconSize: 16,
    headerSwitchHeight: 14,
    headerSwitchThumb: 12,
    headerSwitchTravel: 18,
    headerLabelSize: 10,
    headerControlPadding: 6,
    tabFontSize: 14,
    tabMaxWidth: 280,
    tabHeight: 48,
    logoBoxLeft: 18,
    logoBoxTop: 7,
    logoWidth: 142,
    logoHeight: 32,
    control: 32,
    avatar: 32,
    buttonHeight: 48,
    menuWidth: 548,
    profileWidth: 800,
    profileBannerHeight: 156,
    profilePortrait: 116,
    profileMaxHeight: 800,
    profileRowHeight: 54,
    drawerWidth: 895,
    drawerHeaderHeight: 56,
    tileHeight: 150,
    emptyButtonWidth: 320,
    loginPaneWidth: 690,
    loginFormWidth: 490,
  },
  space: { xs: 4, sm: 8, md: 16, lg: 24, xl: 32 },
  radius: { panel: 6, control: 8, pill: 999 },
  breakpoint: { mobile: 600, tablet: 900 },
  motion: { feedback: '120ms', transition: '180ms', easing: 'ease-out' },
} as const;

export const portalMotionStyles = {
  '@media (prefers-reduced-motion: reduce)': {
    transition: 'none !important',
    animation: 'none !important',
    scrollBehavior: 'auto !important',
  },
} as const;
