import { portalMotionStyles, portalTokens } from './portal-tokens';

/** Profile-only measurements; incomplete artwork retains its documented native offsets. */
export const profileLayout = {
  identityHeight: 148,
  identityInset: 168,
  portraitInset: 26,
  portraitOverlap: 45,
  sectionHeight: 56,
  guideInset: 39,
  smallPortrait: 80,
  smallBanner: 96,
  smallIdentityInset: 116,
  shortViewport: 600,
  viewportInset: 32,
  bannerBandTop: 39,
  bannerLowerLeft: 144,
  bannerBandWidth: 800,
  bannerBandHeight: 72,
  bannerLowerWidth: 656,
  bannerLowerHeight: 117,
  titleInset: 20,
  titleLineHeight: 20,
  borderWidth: 1,
  focusWidth: 2,
  portraitBorder: 2,
  closeGlyph: 20,
  identityTop: 12,
  identityBottom: 16,
  nameLineHeight: 26,
  rowLineHeight: 22,
  sessionLineHeight: 24,
  metadataGlyph: 18,
  sectionGlyphWidth: 20,
  sectionGlyphHeight: 24,
  chipHeight: 22,
  chipLineHeight: 18,
  subjectRowHeight: 51,
  actionGap: 12,
  scrollbarWidth: 12,
  transitionMs: 180,
  type: { title: 14, name: 20, metadata: 14, session: 12, section: 16, row: 14, action: 12 },
} as const;

const profilePalette = {
  light: {
    identityText: '#0d0d0d',
    hierarchy: '#ffffff',
    rowText: '#4d4d4d',
    stripe: '#f9f9f9',
    selected: '#e5f1fc',
    sessionText: '#666666',
  },
  dark: {
    identityText: '#f2f2f2',
    hierarchy: '#262626',
    rowText: '#b2b2b2',
    stripe: '#333333',
    selected: '#00172e',
    sessionText: '#999999',
  },
} as const;

export const getProfileStyles = (mode: 'light' | 'dark', expanded: boolean) => {
  const colors = portalTokens.color[mode];
  const profile = profilePalette[mode];
  const mobile = `@media (max-width: ${portalTokens.breakpoint.mobile}px)`;
  const short = `@media (max-height: ${profileLayout.shortViewport}px)`;
  const baseText = { fontFamily: portalTokens.fontFamily, color: profile.identityText };
  const summary = {
    minHeight: portalTokens.size.profileRowHeight,
    padding: `0 ${portalTokens.space.lg}px`,
    '&.Mui-expanded': { minHeight: portalTokens.size.profileRowHeight },
    '& .MuiAccordionSummary-content, & .MuiAccordionSummary-content.Mui-expanded': {
      margin: `${portalTokens.space.sm}px 0`,
      minWidth: 0,
    },
    '& .MuiAccordionSummary-expandIconWrapper': {
      color: colors.selectedText,
      marginLeft: `${portalTokens.space.sm}px`,
    },
    '& .MuiSvgIcon-root': { fontSize: portalTokens.size.control / 2 },
    '&:hover': { backgroundColor: profile.selected },
    '&.Mui-focusVisible': {
      outline: `${profileLayout.focusWidth}px solid ${portalTokens.color.primary}`,
      outlineOffset: -profileLayout.focusWidth,
    },
    ...portalMotionStyles,
  };
  return {
    paper: {
      ...baseText,
      width: portalTokens.size.profileWidth,
      maxWidth: `calc(100% - ${profileLayout.viewportInset}px)`,
      maxHeight: `calc(100dvh - ${profileLayout.viewportInset}px)`,
      margin: `${portalTokens.space.md}px`,
      height: expanded ? portalTokens.size.profileMaxHeight : 'auto',
      backgroundColor: colors.canvas,
      backgroundImage: 'none',
      border: 0,
      borderRadius: `${portalTokens.radius.panel}px`,
      overflow: 'hidden',
      display: 'flex',
      flexDirection: 'column' as const,
      '& .MuiTypography-root': { fontFamily: portalTokens.fontFamily },
      '& .MuiCollapse-root, & .MuiAccordionSummary-expandIconWrapper': portalMotionStyles,
      [short]: { height: `calc(100dvh - ${profileLayout.viewportInset}px)` },
    },
    banner: {
      height: portalTokens.size.profileBannerHeight,
      flexShrink: 0,
      position: 'relative' as const,
      overflow: 'hidden',
      backgroundColor:
        mode === 'light'
          ? portalTokens.color.headerBackgroundLight
          : portalTokens.color.headerBackgroundDark,
      [short]: { height: profileLayout.smallBanner },
    },
    bannerBand: {
      position: 'absolute' as const,
      left: 0,
      top: profileLayout.bannerBandTop,
      width: profileLayout.bannerBandWidth,
      height: profileLayout.bannerBandHeight,
      pointerEvents: 'none' as const,
    },
    bannerLower: {
      position: 'absolute' as const,
      left: profileLayout.bannerLowerLeft,
      top: profileLayout.bannerBandTop,
      width: profileLayout.bannerLowerWidth,
      height: profileLayout.bannerLowerHeight,
      pointerEvents: 'none' as const,
    },
    title: {
      position: 'relative' as const,
      margin: 0,
      padding: `${profileLayout.titleInset}px ${portalTokens.space.lg}px`,
      fontSize: profileLayout.type.title,
      lineHeight: `${profileLayout.titleLineHeight}px`,
      color: portalTokens.color.headerText,
    },
    close: {
      position: 'absolute' as const,
      top: portalTokens.space.sm,
      right: portalTokens.space.md,
      width: portalTokens.size.control,
      height: portalTokens.size.control,
      color: portalTokens.color.headerMuted,
      '&:hover': { backgroundColor: portalTokens.color.headerControlHover },
      '&.Mui-focusVisible': {
        outline: `${profileLayout.focusWidth}px solid ${portalTokens.color.headerText}`,
      },
      '& .MuiSvgIcon-root': { fontSize: profileLayout.closeGlyph },
      ...portalMotionStyles,
    },
    content: {
      backgroundColor: colors.canvas,
      padding: '0 !important',
      display: 'flex',
      flexDirection: 'column' as const,
      minHeight: 0,
      overflow: 'visible' as const,
      [short]: { overflowY: 'auto' as const },
    },
    identity: {
      position: 'relative' as const,
      flexShrink: 0,
      minHeight: profileLayout.identityHeight,
      padding: `${profileLayout.identityTop}px ${portalTokens.space.lg}px ${profileLayout.identityBottom}px ${profileLayout.identityInset}px`,
      boxSizing: 'border-box' as const,
      backgroundColor: colors.canvas,
      borderBottom: `${profileLayout.borderWidth}px solid ${colors.divider}`,
      [mobile]: {
        paddingLeft: `${profileLayout.smallIdentityInset}px`,
        paddingRight: `${portalTokens.space.md}px`,
      },
    },
    portrait: {
      position: 'absolute' as const,
      top: -profileLayout.portraitOverlap,
      left: profileLayout.portraitInset,
      width: portalTokens.size.profilePortrait,
      height: portalTokens.size.profilePortrait,
      border: `${profileLayout.portraitBorder}px solid ${colors.canvas}`,
      backgroundColor: colors.stripe,
      color: colors.muted,
      [mobile]: {
        width: profileLayout.smallPortrait,
        height: profileLayout.smallPortrait,
        left: portalTokens.space.md,
      },
    },
    name: {
      ...baseText,
      fontSize: profileLayout.type.name,
      lineHeight: `${profileLayout.nameLineHeight}px`,
      fontWeight: 700,
      marginBottom: `${portalTokens.space.sm}px`,
      overflowWrap: 'anywhere' as const,
    },
    metadata: {
      ...baseText,
      display: 'flex',
      alignItems: 'center',
      flexWrap: 'wrap' as const,
      gap: `${portalTokens.space.sm}px`,
      marginBottom: `${portalTokens.space.md}px`,
      '& > span': {
        display: 'inline-flex',
        alignItems: 'center',
        gap: `${portalTokens.space.sm}px`,
        fontSize: profileLayout.type.metadata,
        overflowWrap: 'anywhere' as const,
        minWidth: 0,
      },
      '& > span:not(:first-of-type)': {
        borderLeft: `${profileLayout.borderWidth}px solid ${colors.divider}`,
        paddingLeft: `${portalTokens.space.sm}px`,
      },
      '& svg': {
        width: profileLayout.metadataGlyph,
        height: profileLayout.metadataGlyph,
        flexShrink: 0,
      },
    },
    session: {
      color: profile.sessionText,
      fontSize: profileLayout.type.session,
      lineHeight: `${profileLayout.sessionLineHeight}px`,
      overflowWrap: 'anywhere' as const,
    },
    hierarchy: {
      backgroundColor: profile.hierarchy,
      minHeight: 0,
      overflowY: 'auto' as const,
      flex: '1 1 auto',
      overscrollBehavior: 'contain' as const,
      scrollbarGutter: expanded ? 'stable' : 'auto',
      '&::-webkit-scrollbar': {
        width: profileLayout.scrollbarWidth,
        backgroundColor: profile.hierarchy,
      },
      '&::-webkit-scrollbar-thumb': {
        backgroundColor: colors.muted,
        borderRadius: `${portalTokens.radius.panel}px`,
        border: `${profileLayout.borderWidth * 3}px solid ${profile.hierarchy}`,
      },
      [short]: { flexShrink: 0, overflowY: 'visible' as const },
    },
    section: {
      display: 'flex',
      alignItems: 'center',
      gap: `${portalTokens.space.md}px`,
      minHeight: profileLayout.sectionHeight,
      padding: `0 ${portalTokens.space.lg}px`,
      color: profile.rowText,
      backgroundColor: profile.hierarchy,
      '& .MuiTypography-root': {
        fontSize: profileLayout.type.section,
        fontWeight: 700,
        lineHeight: `${profileLayout.sessionLineHeight}px`,
      },
    },
    accordion: {
      color: profile.rowText,
      backgroundColor: profile.hierarchy,
      backgroundImage: 'none',
      border: 0,
      borderRadius: '0 !important',
      margin: '0 !important',
      '&::before': { display: 'none' },
      boxShadow: 'none',
    },
    summary,
    roleSummary: {
      paddingRight: expanded ? `${profileLayout.scrollbarWidth}px` : `${portalTokens.space.lg}px`,
    },
    subjectSummary: {
      minHeight: profileLayout.subjectRowHeight,
      '&.Mui-expanded': { minHeight: profileLayout.subjectRowHeight },
    },
    selected: { backgroundColor: profile.selected, color: colors.selectedText },
    stripe: { backgroundColor: profile.stripe },
    rowText: {
      fontSize: profileLayout.type.row,
      lineHeight: `${profileLayout.rowLineHeight}px`,
      overflowWrap: 'anywhere' as const,
    },
    roleDetails: {
      padding: 0,
      marginLeft: `${profileLayout.guideInset}px`,
      borderLeft: `${profileLayout.borderWidth}px solid ${colors.divider}`,
    },
    actionDetails: {
      display: 'flex',
      alignItems: 'flex-start',
      flexWrap: 'wrap' as const,
      gap: `${profileLayout.actionGap}px`,
      padding: `${portalTokens.space.lg}px ${portalTokens.space.lg}px ${portalTokens.space.md}px`,
      '& .MuiChip-root': {
        height: 'auto',
        minHeight: profileLayout.chipHeight,
        borderRadius: `${portalTokens.space.xs}px`,
        color: colors.muted,
        backgroundColor: colors.chip,
        maxWidth: '100%',
        fontFamily: portalTokens.fontFamily,
      },
      '& .MuiChip-label': {
        whiteSpace: 'normal',
        overflowWrap: 'anywhere',
        padding: `${profileLayout.borderWidth * 2}px ${portalTokens.space.sm}px`,
        fontSize: profileLayout.type.action,
        lineHeight: `${profileLayout.chipLineHeight}px`,
      },
    },
    empty: {
      color: colors.muted,
      padding: `${portalTokens.space.md}px ${portalTokens.space.lg}px`,
      fontSize: profileLayout.type.row,
    },
  };
};
