import { ComponentNames } from './componentTypes.js';
import { DEFAULT_TYPE, PAGE_TYPE, EMAIL_TYPE } from './constants.js';
export interface ComponentMenuType {
  label: string,
  type: string,
  icon: string,
  id: string,
  display?: string[]
}

export const Categories = ['Input', 'Content', 'Status', 'Business', 'Data Visualisation', 'Layout', 'Action'];

export const PageCategories = ['Content', 'Layout', 'Action'];

export const EmailCategories = ['Input', 'Content', 'Layout', 'Data Visualisation', 'Action'];

const ComponentsDefinition = {
  components: [
    {
      label: 'Text',
      type: 'input',
      icon: 'text',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.TEXTFIELD,
    },
    {
      label: 'Number',
      type: 'input',
      icon: 'number',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.NUMBERINPUT,
    },
    {
      label: 'Label',
      type: 'content',
      icon: 'label',
      display: [DEFAULT_TYPE, PAGE_TYPE, EMAIL_TYPE],
      id: ComponentNames.LABEL,
    },
    {
      label: 'Title',
      type: 'content',
      icon: 'title',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.TITLE,
    },
    {
      label: 'Paragraph',
      type: 'content',
      icon: 'paragraph',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.PARAGRAPH,
    },
    {
      label: 'Time',
      type: 'input',
      icon: 'time',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.TIMEINPUT,
    },
    {
      label: 'Date',
      type: 'input',
      icon: 'date',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.DATEINPUT,
    },
    {
      label: 'Date range',
      type: 'input',
      icon: 'date-range',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.DATERANGEINPUT,
    },
    {
      label: 'Rich text editor',
      type: 'input',
      icon: 'text-editor',
      display: [DEFAULT_TYPE, PAGE_TYPE, EMAIL_TYPE],
      id: ComponentNames.RTE,
    },
    {
      label: 'File',
      type: 'input',
      icon: 'file',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.FILEINPUT,
    },
    {
      label: 'Formatted',
      type: 'input',
      icon: 'formatted-input',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.FORMATTEDINPUT,
    },
    // {
    //   label: 'Card Number',
    //   type: 'input',
    //   icon: 'card-number',
    //   display: [FORM_PAGE_TYPE],
    //   id: ComponentNames.CARDNUMBERINPUT,
    // },
    // {
    //   label: 'Password',
    //   type: 'input',
    //   icon: 'shield--line',
    //   id: ComponentNames.PASSWORDINPUT,
    // },
    // {
    //   label: 'Rating',
    //   type: 'input',
    //   icon: 'rating',
    //   display: [FORM_PAGE_TYPE],
    //   id: ComponentNames.RATING,
    // },
    // {
    //   label: 'Toggle',
    //   type: 'input',
    //   icon: 'toggle',
    //   display: [FORM_PAGE_TYPE],
    //   id: ComponentNames.TOGGLE,
    // },
    {
      label: 'Switch',
      type: 'input',
      icon: 'switch',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.SWITCH,
    },
    {
      label: 'Checkbox',
      type: 'input',
      icon: 'checkbox',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.CHECKBOX,
    },
    {
      label: 'Radio',
      type: 'input',
      icon: 'radio',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.RADIOGROUP,
    },
    {
      label: 'Dropdown',
      type: 'input',
      icon: 'dropdown',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.DROPDOWNINPUT,
    },
    {
      label: 'Multi select',
      type: 'input',
      icon: 'multiple-select',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.DROPDOWNMULTISELECT,
    },
    {
      label: 'Employee',
      type: 'business',
      icon: 'employee-select',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.EMPLOYEEINPUT,
    },
    {
      label: 'Multi employee',
      type: 'business',
      icon: 'employee-select',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.EMPLOYEEMULTIINPUT,
    },
    // {
    //   label: 'Button Group',
    //   type: 'input',
    //   icon: 'button-group',
    //   display: [FORM_PAGE_TYPE],
    //   id: ComponentNames.BUTTONGROUP,
    // },
    {
      label: 'Accordion',
      type: 'content',
      icon: 'accordion',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.ACCORDION,
    },
    {
      label: 'Box',
      type: 'content',
      icon: 'box',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.BOX,
    },
    {
      label: 'Dynamic display',
      type: 'content',
      icon: 'dynamic-display',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.DYNAMICDISPLAY,
    },
    {
      label: 'Banner',
      type: 'content',
      icon: 'banner',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.BANNER,
    },
    {
      label: 'Image',
      type: 'content',
      icon: 'image',
      display: [DEFAULT_TYPE, PAGE_TYPE, EMAIL_TYPE],
      id: ComponentNames.IMAGE,
    },
    {
      label: 'Carousel',
      type: 'content',
      icon: 'carousel',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.CAROUSEL,
    },
    {
      label: 'Tabs',
      type: 'layout',
      icon: 'tabs',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.TABS,
    },
    {
      label: 'Stepper',
      type: 'status',
      icon: 'stepper',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.STEPPER,
    },
    {
      label: 'Tag',
      type: 'status',
      icon: 'tag',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.TAG,
    },
    {
      label: 'Icon',
      type: 'status',
      icon: 'icon',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.ICON,
    },
    {
      label: 'Progress bar',
      type: 'status',
      icon: 'progress-bar',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.PROGRESSBAR,
    },
    {
      label: 'Spinner',
      type: 'status',
      icon: 'spinner',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.SPINNER,
    },
    {
      label: 'Content loader',
      type: 'status',
      icon: 'content-loader',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.CONTENTLOADER,
    },
    // {
    //   label: 'Repeater',
    //   type: 'action',
    //   icon: 'repeater',
    //   display: [DEFAULT_TYPE, PAGE_TYPE],
    //   id: ComponentNames.REPEATER,
    // },
    {
      label: 'Divider',
      type: 'layout',
      icon: 'divider',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.DIVIDER,
    },
    {
      label: 'Spacer',
      type: 'layout',
      icon: 'spacer',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.SPACER,
    },
    {
      label: '1 column',
      type: 'layout',
      icon: 'grid1x1',
      display: [DEFAULT_TYPE, PAGE_TYPE, EMAIL_TYPE],
      id: ComponentNames.GRID1COLUMN,
    },
    {
      label: '2 columns',
      type: 'layout',
      icon: 'grid1x2',
      display: [DEFAULT_TYPE, PAGE_TYPE, EMAIL_TYPE],
      id: ComponentNames.GRID2COLUMNS,
    },
    {
      label: '3 columns',
      type: 'layout',
      icon: 'grid1x3',
      display: [DEFAULT_TYPE, PAGE_TYPE, EMAIL_TYPE],
      id: ComponentNames.GRID3COLUMNS,
    },
    {
      label: 'Table',
      type: 'data visualisation',
      icon: 'table',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.TABLE,
    },
    {
      label: 'Data view',
      type: 'data visualisation',
      icon: 'data-view',
      display: [EMAIL_TYPE],
      id: ComponentNames.DATAVIEW,
    },
    {
      label: 'Button',
      type: 'action',
      icon: 'button',
      display: [DEFAULT_TYPE, PAGE_TYPE, EMAIL_TYPE],
      id: ComponentNames.BUTTON,
    },
    {
      label: 'Link',
      type: 'action',
      icon: 'link',
      display: [DEFAULT_TYPE, PAGE_TYPE, EMAIL_TYPE],
      id: ComponentNames.LINK,
    },
    {
      label: 'Document viewer',
      type: 'content',
      icon: 'document-viewer',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.DOCUMENTVIEWER,
    },
    {
      label: 'Date display',
      type: 'content',
      icon: 'date-display',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.DATEDISPLAY,
    },
    {
      label: 'Comments',
      type: 'content',
      icon: 'comments',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.COMMENTS,
    },
    {
      label: 'Modal',
      type: 'content',
      icon: 'modal',
      display: [DEFAULT_TYPE, PAGE_TYPE],
      id: ComponentNames.MODAL,
    },
  ],
};

export default ComponentsDefinition;
