export default {
  rootDir: '.',
  testEnvironment: 'jsdom',
  setupFilesAfterEnv: ['<rootDir>/src/test-setup.ts'],
  testMatch: ['<rootDir>/src/application.test.tsx', '<rootDir>/src/compat/**/*.test.ts'],
  transform: { '^.+\\.(j|t)sx?$': 'babel-jest' },
  transformIgnorePatterns: ['node_modules/(?!(@fm)/)'],
  moduleNameMapper: {
    '^@migrated-cashflow-cn$': '<rootDir>/src/test/legacy-cashflow-cn-stub.tsx',
    '^@fm/ratan-design-webkit$': '<rootDir>/src/test/ratan-webkit-stub.tsx',
    '^react$': '<rootDir>/node_modules/react',
    '^react/(.*)$': '<rootDir>/node_modules/react/$1',
    '^react-dom$': '<rootDir>/node_modules/react-dom',
    '^react-dom/(.*)$': '<rootDir>/node_modules/react-dom/$1',
    '\\.(css)$': 'identity-obj-proxy',
  },
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    '!src/compat/**',
    '!src/test/**',
    '!src/types/**',
    '!src/migrated-entry.tsx',
    '!src/Cashflow_CN/**',
    '!src/Cashflow_Dashboard/**',
    '!src/Root/**',
    '!src/generated/**',
    '!src/index.tsx',
    '!src/standalone.ts',
    '!src/test-setup.ts',
  ],
  coverageDirectory: './coverage',
  coverageReporters: ['text', 'lcov'],
  coverageThreshold: {
    global: { lines: 90, branches: 85, functions: 90, statements: 90 },
  },
};
