/**
 * @fileoverview Microfrontend Root Module
 *
 * This is the main entry point for the base microfrontend application.
 * It configures single-spa lifecycle functions and exports all public
 * modules that can be consumed by other microfrontends or applications.
 *
 * The module provides:
 * - Single-spa lifecycle hooks (bootstrap, mount, unmount)
 * - Standalone rendering capabilities
 * - Re-exports of all public components, hooks, and utilities
 *
 * @module root
 * @see {@link https://single-spa.js.org/docs/building-applications} Single-spa Documentation
 */

import React from 'react';
import ReactDOMClient from 'react-dom/client';
import singleSpaReact from 'single-spa-react';
import App from './App';
import './styles/tailwind.css';

// =============================================================================
// Single-spa Lifecycle Configuration
// =============================================================================

/**
 * Single-spa lifecycle hooks generated by single-spa-react.
 * These hooks manage the application's lifecycle within the single-spa ecosystem.
 *
 * @see {@link https://single-spa.js.org/docs/building-applications#registered-application-lifecycle}
 */
const lifecycles = singleSpaReact({
  React,
  ReactDOMClient,
  rootComponent: App,
  /**
   * Custom error boundary for the microfrontend.
   * Displays error message when the application crashes.
   *
   * @param err - The error that was caught
   * @returns A React element displaying the error message
   */
  errorBoundary(err) {
    // Customize the root error boundary for your microfrontend here.
    return <span>{err.message}</span>;
  },
});

/**
 * Bootstrap lifecycle hook.
 * Called once when the application is first loaded (before mount).
 * Used for one-time initialization.
 */
export const { bootstrap, unmount } = lifecycles;

/**
 * Reference to the container element ID for standalone mounting.
 * This is set by the host application via window.single_spa_container_id.
 */
const rootElement = window.single_spa_container_id;

/**
 * Renders the App component into a given DOM element.
 * Used for standalone rendering outside of single-spa.
 *
 * @param rootComp - The DOM element to render into
 * @param props - Props to pass to the App component
 */
export const render = (rootComp, props) => {
  const root = ReactDOMClient.createRoot(rootComp);
  root.render(<App {...props} />);
};

/**
 * Conditionally renders the app if a root element exists.
 *
 * @param rootComp - The DOM element to check and render into
 * @param props - Props to pass to the App component
 */
export const check = (rootComp, props) => {
  if (rootComp) {
    render(rootComp, props);
  }
};

/**
 * Mounts the component when running in standalone mode.
 * Returns a Promise to comply with single-spa lifecycle interface.
 *
 * @param props - Props to pass to the App component
 * @returns A Promise that resolves after mounting
 */
export function MountComponent(props) {
  return Promise.resolve().then(() => {
    check(rootElement, props);
  });
}

/**
 * Mount lifecycle hook.
 * Uses custom MountComponent if running standalone, otherwise uses single-spa's mount.
 * Called each time the application should be displayed.
 */
export const mount = rootElement ? MountComponent : lifecycles.mount;

// =============================================================================
// React Router Exports
// =============================================================================

/** Re-export react-router-dom for use by consuming applications */
export * as ReactRouterDom from 'react-router-dom';

// =============================================================================
// Analytics Exports
// =============================================================================

/** Analytics tracking utilities and configurations */
export * as Analytics from './analytics';

// =============================================================================
// UI Component Exports
// These components are the building blocks for the application UI
// =============================================================================

/** Builder button component for admin interfaces */
export * as BuilderButton from './components/BuilderButton';

/** Standard button component with MUI styling */
export * as Button from './components/Button';

/** Date picker component using MUI date pickers */
export * as DatePicker from './components/DatePicker';

/** Date range picker for selecting date intervals */
export * as DateRangePicker from './components/DateRangePicker';

/** Combined date and time picker component */
export * as DateTimePicker from './components/DateTimePicker';

/** Modal dialog component for overlays and confirmations */
export * as Dialog from './components/Dialog';

/** Navigation drawer/sidebar component */
export * as Drawer from './components/Drawer';

/** Error boundary component for catching render errors */
export * as ErrorBoundry from './components/ErrorBoundry';

/** Text input component with validation support */
export * as Input from './components/Input';

/** Label component for form fields */
export * as Label from './components/Label';

/** Loading spinner component */
export * as Loader from './components/Loader';

/** Loader component prop types */
export * as LoaderProps from './components/Loader/common/type';

/** Full-page loading overlay */
export * as PageLoader from './components/Loader/PageLoader';

/** Button with built-in loading state */
export * as LoadingButton from './components/LoadingButton';

/** Loading button prop types */
export * as LoadingButtonProps from './components/LoadingButton/interface';

/** Button to reset form or state */
export * as ResetButton from './components/ResetButton';

/** Smart Card WebKit integration component */
export * as ScWebkit from './components/ScWebkit';

/** Search trigger button component */
export * as SearchButton from './components/SearchButton';

/** Individual search condition field */
export * as SearchCondition from './components/SearchCondition';

/** Container for multiple search conditions */
export * as SearchConditionContainer from './components/SearchConditionContainer';

/** Data grid with search functionality */
export * as SearchGrid from './components/SearchGrid';

/** Search input field component */
export * as SearchInput from './components/SearchInput';

/** Dropdown select component */
export * as Select from './components/Select';

/** Toast notification component */
export * as Snackbar from './components/Snackbar';

/** Splash screen/loading screen component */
export * as Splash from './components/Splash';

/** Time display component */
export * as Time from './components/Time';

/** Time picker input component */
export * as TimePicker from './components/TimePicker';

/** Toggle button group component */
export * as ToggleButton from './components/ToggleButton';

/** Version display component */
export * as Version from './components/Version';

// =============================================================================
// Hook Exports
// Custom React hooks for state management and side effects
// =============================================================================

/** Collection of all custom React hooks */
export * as Hooks from './hooks';

/** Action dispatcher utilities for state management */
export * as Dispatcher from './hooks/dispathcer';

/** Context provider for global application state */
export * as Provider from './hooks/provider';

/** Reducer functions for state management */
export * as Reduces from './hooks/reducer';

/** Action type constants for reducers */
export * as ActionType from './hooks/reducer/util/ActionType';

/** API service hooks for data fetching */
export * as Service from './hooks/service';

/** Extended service utilities */
export * as ExtendService from './hooks/service/util/extend';

// =============================================================================
// Service Exports
// =============================================================================

/** API service layer for backend communication */
export * as Services from './services';

// =============================================================================
// Theme Exports
// =============================================================================

/** Theme configuration options */
export * as ThemeConfig from './theme/Config';

/** Theme utility functions */
export * as ThemeUtil from './theme/config/utils';

/** MUI Theme provider component */
export * as ThemeProvider from './theme/Provider';

// =============================================================================
// Utility Exports
// =============================================================================

/** Common utility functions */
export * as CommonUtil from './utils/common';

/** Drawer/channel navigation utilities */
export * as ChannelUtil from './utils/drawer';

/** Internationalization/locale utilities */
export * as LocaleUtil from './utils/locale';

/** Authentication and login utilities */
export * as LoginUtil from './utils/login';

/** React component wrapper utilities */
export * as ReactWrapper from './utils/ReactWrapper';

/** FDC3 Agent */
export * as FDC3Agent from './fdc3/expose';