import { Enum } from './enum.js';

export interface CUSTOM_EVENTS_TYPE {
  'sc-post': string,
  'sc-action': string,
  'sc-change': string,
  'sc-loaded': string,
  'sc-select': string,
  'sc-calendar-view-change': string,
  'sc-case-search': string,
  'sc-case-export': string,
  'sc-case-click': string,
  'sc-case-form-data-change': string,
  'sc-case-action': string,
  'sc-case-attachments-changed': string,
  'sc-case-comments-changed': string,
  'sc-case-links-changed': string,
  'sc-case-history-item-select': string,
  'sc-case-back': string,
  'sc-case-create': string,
  'sc-input': string,
  'sc-clear': string,
  'sc-card-click': string,
  'sc-comment-filter': string,
  'sc-comment-like': string,
  'sc-comment-share': string,
  'sc-comment-report': string,
  'sc-comment-file-upload': string,
  'sc-comment-file-delete': string,
  'sc-comment-file-download': string,
  'sc-comment-file-error': string,
  'sc-filter-change': string,
  'sc-sort-change': string,
  'sc-view-sort-change': string,
  'sc-toggle-replies': string,
  'sc-reply': string,
  'sc-edit': string,
  'sc-delete-request': string,
  'sc-submit': string,
  'sc-cancel': string,
  'sc-close': string,
  'sc-compact-change': string,
  'sc-files-change': string,
  'sc-file-error': string,
  'sc-action-trigger': string,
  'sc-reminder-trigger': string,
  'sc-hover-end': string,
  'sc-attachment-download': string,
  'sc-attachment-preview': string,
  'sc-userinfo-load': string,
  'sc-load-more': string,
  'sc-collapse': string,
  'sc-expand': string,
  'sc-zoom': string,
  'sc-pan': string,
  'sc-hover': string,
  'sc-resize': string,
  'sc-export': string,
  'sc-rel-draw': string,
  'sc-rel-update': string,
  'sc-rel-animating': string,
  'sc-rel-animated': string,
  'sc-rel-depth': string,
  'sc-rel-search-select': string,
  'sc-draft-change': string,
  'sc-compact-draft-change': string,
  'sc-submit-success': string,
  'sc-submit-error': string,
}

export enum CUSTOM_EVENTS {
  'sc-post' = 'sc-post',
  'sc-action' = 'sc-action',
  'sc-change' = 'sc-change',
  'sc-loaded' = 'sc-loaded',
  'sc-select' = 'sc-select',
  'sc-calendar-view-change' = 'sc-calendar-view-change',
  'sc-case-search' = 'sc-case-search',
  'sc-case-export' = 'sc-case-export',
  'sc-case-click' = 'sc-case-click',
  'sc-case-form-data-change' = 'sc-case-form-data-change',
  'sc-case-action' = 'sc-case-action',
  'sc-case-attachments-changed' = 'sc-case-attachments-changed',
  'sc-case-comments-changed' = 'sc-case-comments-changed',
  'sc-case-links-changed' = 'sc-case-links-changed',
  'sc-case-history-item-select' = 'sc-case-history-item-select',
  'sc-case-back' = 'sc-case-back',
  'sc-case-create' = 'sc-case-create',
  'sc-input' = 'sc-input',
  'sc-clear' = 'sc-clear',
  'sc-card-click' = 'sc-card-click',
  'sc-comment-filter' = 'sc-comment-filter',
  'sc-comment-like' = 'sc-comment-like',
  'sc-comment-share' = 'sc-comment-share',
  'sc-comment-report' = 'sc-comment-report',
  'sc-comment-file-upload' = 'sc-comment-file-upload',
  'sc-comment-file-delete' = 'sc-comment-file-delete',
  'sc-comment-file-download' = 'sc-comment-file-download',
  'sc-comment-file-error' = 'sc-comment-file-error',
  'sc-filter-change' = 'sc-filter-change',
  'sc-sort-change' = 'sc-sort-change',
  'sc-view-sort-change' = 'sc-view-sort-change',
  'sc-toggle-replies' = 'sc-toggle-replies',
  'sc-reply' = 'sc-reply',
  'sc-edit' = 'sc-edit',
  'sc-delete-request' = 'sc-delete-request',
  'sc-submit' = 'sc-submit',
  'sc-cancel' = 'sc-cancel',
  'sc-close' = 'sc-close',
  'sc-compact-change' = 'sc-compact-change',
  'sc-files-change' = 'sc-files-change',
  'sc-file-error' = 'sc-file-error',
  'sc-action-trigger' = 'sc-action-trigger',
  'sc-reminder-trigger' = 'sc-reminder-trigger',
  'sc-hover-end' = 'sc-hover-end',
  'sc-attachment-download' = 'sc-attachment-download',
  'sc-attachment-preview' = 'sc-attachment-preview',
  'sc-collapse' = 'sc-collapse',
  'sc-expand' = 'sc-expand',
  'sc-zoom' = 'sc-zoom',
  'sc-pan' = 'sc-pan',
  'sc-hover' = 'sc-hover',
  'sc-resize' = 'sc-resize',
  'sc-export' = 'sc-export',
  'sc-rel-draw' = 'sc-rel-draw',
  'sc-rel-update' = 'sc-rel-update',
  'sc-rel-animating' = 'sc-rel-animating',
  'sc-rel-animated' = 'sc-rel-animated',
  'sc-rel-depth' = 'sc-rel-depth',
  'sc-rel-search-select' = 'sc-rel-search-select',
  'sc-draft-change' = 'sc-draft-change',
  'sc-compact-draft-change' = 'sc-compact-draft-change',
  'sc-load-more' = 'sc-load-more',
}


const events = [
  'sc-rel-update',
  'sc-rel-draw',
  'sc-rel-render',
] as const;
export const INTERNAL_EVENTS = Enum(events);
INTERNAL_EVENTS.reverse;