// cashflow
export const SET_CASHFLOW_GRID_EVENT: string = "SET_CASHFLOW_GRID_EVENT";
export const SET_CASHFLOW_LIST: string = "SET_CASHFLOW_LIST";
export const SET_INIT_PARAMS = "SET_INIT_PARAMS";

export const ACTION_TYPE_SET_SEARCH_FILTERS: string =
  "ACTION_TYPE_SET_SEARCH_FILTERS";
export const ACTION_TYPE_SET_QUICK_FILTERS: string =
  "ACTION_TYPE_SET_QUICK_FILTERS";
export const ACTION_TYPE_SET_ADVANCED_SEARCH =
  "ACTION_TYPE_SET_ADVANCED_SEARCH";
export const ACTION_TYPE_SWITCH_SEARCH: string = "ACTION_TYPE_SWITCH_SEARCH";

export const SHOW_HIDE_CASHFLOW_SEARCH_BAR: string =
  "SHOW_HIDE_CASHFLOW_SEARCH_BAR";

export const ADHOC_SSI_WORKFLOW = "ADHOC_SSI_WORKFLOW";
export const ADHOC_NOSTRO_WORKFLOW = "ADHOC_NOSTRO_WORKFLOW";
export const ADD_COMMENT_WORKFLOW = "ADD_COMMENT_WORKFLOW";
export const NET_WORKFLOW = "NET_WORKFLOW";
export const UN_NET_WORKFLOW = "UN_NET_WORKFLOW";
export const SPLITTING_WORKFLOW = "SPLITTING_WORKFLOW";
export const SPLITTING_CASHFLOW_FINISHED = "SPLITTING_CASHFLOW_FINISHED";
export const SPLITTING_VALIDATION = "SPLITTING_VALIDATION";
export const UPDATE_AFFIRMATION_STATUS = "UPDATE_AFFIRMATION_STATUS";
export const VIEW_CASHFLOW_DETAILS = "VIEW_CASHFLOW_DETAILS";
export const VIEW_TRADE_DETAILS = "VIEW_TRADE_DETAILS";

export const UPDATE_NET_DATAGRID_DEF = "UPDATE_NET_DATAGRID_DEF";
export const NET_CASHFLOW_FINISHED = "NET_CASHFLOW_FINISHED";

export const SET_CASHFLOW_LIST_PAGINATION = "SET_CASHFLOW_LIST_PAGINATION";
export const SET_CASHFLOW_LIST_QUERY_STATUS = "SET_CASHFLOW_LIST_QUERY_STATUS";

export const HOLD_WORKFLOW = "HOLD_WORKFLOW";

export const EARLY_MATERIALIZATION_WORKFLOW = "EARLY_MATERIALIZATION_WORKFLOW";

export const COMMON_COMMENT_ACTION_WORKFLOW = "COMMON_COMMENT_ACTION_WORKFLOW";

export const SUPPRESS_WORKFLOW = "SUPPRESS_WORKFLOW";
export const MANUAL_SETTLE_WORKFLOW = "MANUAL_SETTLE_WORKFLOW";

export const SET_DIALOG_REFRESH_ALERT = "SET_DIALOG_REFRESH_ALERT";

export const LATEST_NOTIFICATION_STACK = "LATEST_NOTIFICATION_STACK";

export const CASHFLOW_LIST_QUERY_ID = "CASHFLOW_LIST_QUERY_ID";

export const CASHFLOW_LIST_QUERY_PAGE_SIZE = "CASHFLOW_LIST_QUERY_PAGE_SIZE";

export const OPEN_BULK_FIX_EXCEPTION_DIALOG = "OPEN_BULK_FIX_EXCEPTION_DIALOG";
export const CLOSE_BULK_FIX_EXCEPTION_DIALOG =
  "CLOSE_BULK_FIX_EXCEPTION_DIALOG";
export const LOAD_NEXT_PAGE = "LOAD_NEXT_PAGE";

export const OPENSEARCH = "OPENSEARCH";

export const OPEN_SETTLEMENT_METHOD_UPDATE_DIALOG =
  "OPEN_SETTLEMENT_METHOD_UPDATE_DIALOG";
export const CLOSE_SETTLEMENT_METHOD_UPDATE_DIALOG =
  "CLOSE_SETTLEMENT_METHOD_UPDATE_DIALOG";
