/** Base-owned branding, compact geometry and semantic text roles. */
export const portalTokens = {
  fontFamily: '"SC Prosper Sans", Arial, sans-serif',
  typography: {
    pageHeading: { fontSize: 32, lineHeight: '40px' },
    sectionHeading: { fontSize: 16, lineHeight: '24px' },
    title: { fontSize: 20, lineHeight: '26px' },
    body: { fontSize: 14, lineHeight: '20px' },
    caption: { fontSize: 12, lineHeight: '18px' },
    heroHeading: { fontSize: 28, lineHeight: '36px' },
    heroBody: { fontSize: 16, lineHeight: '24px' },
  },
  color: {
    primary: '#0473ea',
    primaryHover: '#025dbd',
    primaryText: '#ffffff',
    headerText: '#e5f1fc',
    headerMuted: '#b3d5f8',
    headerControl: 'rgba(179, 213, 248, 0.28)',
    headerControlHover: 'rgba(179, 213, 248, 0.44)',
    headerBackgroundLight: '#020b43',
    headerBackgroundDark: '#012e5d',
    headerBackgroundDarkGlow: '#013771',
    headerIconFilter:
      'brightness(0) saturate(100%) invert(88%) sepia(13%) saturate(543%) hue-rotate(178deg) brightness(103%) contrast(98%)',
    backdrop: 'rgba(0, 0, 0, 0.54)',
    light: {
      canvas: '#ffffff',
      text: '#1a1a1a',
      muted: '#666666',
      divider: '#cccccc',
      stripe: '#f8f8f8',
      selected: '#e5f1fc',
      selectedText: '#0250a3',
      chip: '#e5e5e5',
    },
    dark: {
      canvas: '#1a1a1a',
      text: '#eeeeee',
      muted: '#b0b0b0',
      divider: '#666666',
      stripe: '#303030',
      selected: '#001c33',
      selectedText: '#e5f1fc',
      chip: '#151515',
    },
  },
  size: {
    headerHeight: 94,
    headerToolbarHeight: 46,
    headerMobileHeight: 140,
    headerIconSize: 16,
    headerSwitchHeight: 14,
    headerSwitchThumb: 12,
    headerSwitchTravel: 18,
    headerLabelSize: 10,
    headerControlPadding: 6,
    tabFontSize: 14,
    tabMaxWidth: 280,
    tabHeight: 48,
    logoBoxLeft: 18,
    logoBoxTop: 7,
    logoWidth: 142,
    logoHeight: 32,
    control: 32,
    avatar: 32,
    buttonHeight: 48,
    menuWidth: 320,
    profileWidth: 800,
    profileBannerHeight: 156,
    profilePortrait: 116,
    profileMaxHeight: 800,
    profileRowHeight: 48,
    drawerWidth: 895,
    drawerHeaderHeight: 56,
    tileHeight: 125,
    emptyButtonWidth: 320,
    loginPaneWidth: 690,
    loginFormWidth: 360,
    loginControlHeight: 44,
    touchControl: 44,
  },
  space: { xs: 4, sm: 8, md: 16, lg: 24, xl: 32 },
  radius: { panel: 6, control: 8, pill: 999 },
  breakpoint: { mobile: 600, tablet: 900 },
  motion: { feedback: '120ms', transition: '180ms', easing: 'ease-out' },
} as const;

const previewTypography = (role: string, defaults: { fontSize: number; lineHeight: string }) => ({
  fontSize: `var(--portal-preview-${role}-font-size, ${defaults.fontSize}px)`,
  lineHeight: `var(--portal-preview-${role}-line-height, ${defaults.lineHeight})`,
});

/** Optional dev-preview values; structural geometry retains the compact defaults. */
export const portalPresentationTokens = {
  ...portalTokens,
  fontFamily: `var(--portal-preview-font-family, ${portalTokens.fontFamily})`,
  typography: {
    pageHeading: previewTypography('page-heading', portalTokens.typography.pageHeading),
    sectionHeading: previewTypography('section-heading', portalTokens.typography.sectionHeading),
    title: previewTypography('title', portalTokens.typography.title),
    body: previewTypography('body', portalTokens.typography.body),
    caption: previewTypography('caption', portalTokens.typography.caption),
    heroHeading: previewTypography('hero-heading', portalTokens.typography.heroHeading),
    heroBody: previewTypography('hero-body', portalTokens.typography.heroBody),
  },
  color: {
    ...portalTokens.color,
    primary: `var(--portal-preview-primary, ${portalTokens.color.primary})`,
    primaryHover: `var(--portal-preview-primary-hover, ${portalTokens.color.primaryHover})`,
    primaryText: `var(--portal-preview-primary-text, ${portalTokens.color.primaryText})`,
  },
  size: {
    ...portalTokens.size,
    headerLabelSize: `var(--portal-preview-header-label-font-size, ${portalTokens.size.headerLabelSize}px)`,
    tabFontSize: `var(--portal-preview-tab-font-size, ${portalTokens.size.tabFontSize}px)`,
  },
  radius: {
    ...portalTokens.radius,
    control: `var(--portal-preview-control-radius, ${portalTokens.radius.control}px)`,
  },
} as const;

export const portalMotionStyles = {
  '@media (prefers-reduced-motion: reduce)': {
    transition: 'none !important',
    animation: 'none !important',
    scrollBehavior: 'auto !important',
  },
} as const;
