export const Queries = {
  customer: ['acqChannel', 'armCode',
    'bsbdaFlag', 'checkerDeptCode', 'closeReasonCode', 'closingId', 'countryId', 'createdAt',
    'custNatCode', 'dedupReasonCode', 'dedupRefNum', 'demisedDate', 'dob',
    'fName', 'fullName', 'fullNameOverrideFlag', 'gender', 'groupId', 'groupName',
    'homeBranch', 'interfaceId', 'lName', 'lNameOverrideFlag', 'lNameStatChangeDate', 'midName',
    'prevCoreBankId', 'profileActivationDate', 'profilePurgDate', 'profileType',
    'refByRelName', 'refByRelNo', 'referenceId', 'referralId', 'relationshipStatus', 'reOpenCounter',
    'reOpenIndicator', 'reqCountryCode', 'residentCountry', 'residentStatus', 'revisionNumber', 
    'salCode', 'segmentCode', 'senCitiFlag', 'senderBranch', 'senderId', 'serviceIndicatorCode',
    'sourcingId', 'status', 'statusAt', 'subSegCode', 'trackingId', 'updatedAt'],
  contact: ['alertRequiredForContactAmendment', 'alertSuppressReasonCode', 'areaCode',
    'attentionParty', 'contact', 'contactClassificationCode', 'contactInvalidIndicator',
    'contactType', 'countryCode', 'countryId', 'createdAt', 'customContactNo',
    'doNotDisturbExpiryDate', 'doNotDisturbLastUpdatedDate', 'doNotDisturbRegistry',
    'extensionDet', 'homeOfficeIdentifier', 'interfaceId', 'isdContactCountryCode',
    'preferredContact', 'primaryContact', 'reference', 'referenceId', 'requestCountryCode',
    'senderBranch', 'senderId', 'sequenceNumber', 'status', 'statusAt', 'trackingId', 'updatedAt'],
  address: ['addclassificationCode', 'addressInvalidIndicator', 'addressLineOne', 'addressLineThree',
    'addressLineTwo', 'addressType', 'addressTypeDescription', 'alertReqForAddAmend',
    'alertSuppReasonCode', 'cityName', 'consolidateStmtFlag', 'countryCode', 'countryId',
    'displayOrder', 'interfaceId', 'isMailingAddress', 'langId', 'locGovArea',
    'nearestLandMark', 'poaDocument', 'postalCode', 'postBoxNo', 'referenceId', 'reqCountryCode',
    'resetRetMailCounter', 'returnMailCounter', 'senderBranch', 'senderId', 'state', 'stateCode',
    'status', 'statusAt', 'trackingId'],
  risk: ['referenceId', { riskDetails: [
    'createdAt', 'reviewPeriod', 'riskCode', 'riskExpiryDate', 'riskReasonRemarks', 'riskStartDate',
    'riskType', 'senderBranch', 'senderId', 'status', 'statusAt', 'updatedAt',
  ] }],
};