package com.sc.api.generated.providers;

import jakarta.ws.rs.WebApplicationException;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.ext.ParamConverter;
import jakarta.ws.rs.ext.ParamConverterProvider;
import jakarta.ws.rs.ext.Provider;

import org.joda.time.LocalDate;

import java.lang.annotation.Annotation;
import java.lang.reflect.Type;

/*
    This file was generated by sc-devkit, please do not delete it. It will be checked when syncing the project with the openapi spec.

    You must use this file in your project, eg.
    interfaces -> your code must implement them to ensure that the correct @Path is exposed in the REST application so that it conforms to the open api specification.
    models/records -> you must return the response using the following schemas since it is defined in the open api spec. This helps prevent your code from drifting from the open api spec.
*/

@Provider
public class JodaLocalDateProvider implements ParamConverterProvider {

    public static class JodaLocalDateConverter implements ParamConverter<LocalDate> {

        public LocalDate fromString(String string) {
            try {
                LocalDate localDate = LocalDate.parse(string);
                return localDate;
            } catch (Exception e) {
                throw new WebApplicationException(
                        Response.status(Response.Status.BAD_REQUEST)
                                .entity(string + " must be valid LocalDate")
                                .build());
            }
        }

        public String toString(LocalDate t) {
            return t.toString();
        }
    }

    public <T> ParamConverter<T> getConverter(Class<T> type, Type type1, Annotation[] antns) {
        if (LocalDate.class.equals(type)) {
            return (ParamConverter<T>) new JodaLocalDateConverter();
        }
        return null;
    }
}
